"""oq-pfdha web GUI — prototype front-end (Streamlit).

A working web interface for Probabilistic Fault Displacement Hazard
Analysis: it assembles a real job (INI + NRML source-model logic tree +
NRML FDHA logic tree) from the form inputs and executes the actual
oq-pfdha engine (`FdhaLogicTree.from_ini(...).run(...)`) — the same code
path as the `fdha` command line.

Model lists and per-model parameter documentation come from registry.json,
a snapshot of the actual model registry and User-Manual parameter tables
generated by generate_registry.py.

Requires the oq-pfdha package installed (pip install -e . at the repo
root) plus webgui_demo/requirements.txt.

Run:  streamlit run webgui_demo/app.py
"""
from __future__ import annotations

import datetime as _dt
import io
import json
import logging
import shutil
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path

import streamlit as st

HERE = Path(__file__).parent
REPO = HERE.parent
RUNS = HERE / "runs"
REGISTRY = json.loads((HERE / "registry.json").read_text())

# Display order/labels for the four logic-tree slots
# (uncertaintyType values from openquake/fdha/logic_tree/types.py:7-12).
SLOT_LABELS = {
    "fdhaPrimarySRModel": "1 — Principal surface rupture (probability)",
    "fdhaPrimaryFDModel": "2 — Principal fault displacement",
    "fdhaSecondarySRModel": "3 — Distributed surface rupture (probability)",
    "fdhaSecondaryFDModel": "4 — Distributed fault displacement",
}

# Light-calculation default: the Youngs-2003 chain of the Norcia Case 3
# benchmark logic tree (config_norcia_case3_iaea_fdha_logic_tree.xml) —
# a single end-branch that completes in well under a minute.
LIGHT_PRESET = {
    "fdhaPrimarySRModel": ["Youngs2003PrimarySR"],
    "fdhaPrimaryFDModel": ["Youngs2003PrimaryFD"],
    "fdhaSecondarySRModel": ["Youngs2003SecondarySR"],
    "fdhaSecondaryFDModel": ["Youngs2003SecondaryFD"],
}

# Built-in source models shipped with the repository. Geometry defaults are
# the ones used by the corresponding in-repo jobs.
BUILTIN_SOURCES = {
    "Norcia Case 3 (IAEA TECDOC-2092)": {
        "xml": REPO / "openquake/fdha/test/benchmark/norcia_case3_iaea/source_model_norcia_case3.xml",
        # job_norcia_case3_iaea_curve.ini:6 / _map.ini:6-8
        "sites": "13.278 42.767, 13.188 42.749, 13.212 42.853",
        "region": "13.05 42.65, 13.35 42.65, 13.35 42.95, 13.05 42.95",
        "grid": 0.005, "max_dist": 50.0, "vs30": 760.0,
    },
    "Minimal example (single simple fault)": {
        "xml": REPO / "examples/source_model.xml",
        # examples/hazard_curve_minimal.ini:6
        "sites": "16.16573727 39.64704451",
        "region": "16.0 39.5, 16.35 39.5, 16.35 39.8, 16.0 39.8",
        "grid": 0.01, "max_dist": 50.0, "vs30": 760.0,
    },
}

# Default displacement levels: job_norcia_case3_iaea_curve.ini:17
DEFAULT_DML = ('{"FD": [0.0001, 0.001, 0.005, 0.01, 0.015, 0.03, 0.05, '
               '0.075, 0.1, 0.15, 0.3, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, '
               '5.0, 7.5, 10.0]}')

# Weight tolerance mirrors validator rule FDLT-001
# (openquake/fdha/logic_tree/validators.py:133-143).
WEIGHT_TOL = 1e-6

st.set_page_config(page_title="oq-pfdha GUI", page_icon="🌍", layout="wide")


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------
def list_sources(xml_path: Path) -> list[dict]:
    """Parse an NRML source model and list its fault sources (id/name/rake)."""
    ns = {"n": "http://openquake.org/xmlns/nrml/0.4",
          "n5": "http://openquake.org/xmlns/nrml/0.5"}
    root = ET.parse(xml_path).getroot()
    out = []
    for elem in root.iter():
        tag = elem.tag.split("}")[-1]
        if tag.endswith("FaultSource"):
            rake_el = elem.find(".//n:rake", ns) or elem.find(".//n5:rake", ns)
            rake = float(rake_el.text) if rake_el is not None else None
            style = ""
            if rake is not None:
                # rake -> style classification convention used by the engine
                if -135 <= rake <= -45:
                    style = "normal"
                elif 45 <= rake <= 135:
                    style = "reverse"
                else:
                    style = "strike-slip"
            out.append({"id": elem.get("id"), "name": elem.get("name"),
                        "type": tag, "rake": rake, "style": style})
    return out


def build_fdha_lt_xml(primary: dict, pairs: list) -> str:
    """Serialize the selection to one NRML logic-tree XML (schema per
    openquake/fdha/logic_tree/nrml_reader.py:24-56).

    Primary SR and primary FD are independent branch sets (full Cartesian
    product, as in the Taiwan example tree). Distributed models are locked
    (SR, FD) pairs: one SR branch per pair at level 3, and per-pair FD
    branch sets chained with applyToBranches at level 4 — mirroring the
    Norcia Case 3 and Taiwan trees. This guarantees engine-compatible
    combinations (the Visini et al. 2025 FD model can only run on top of
    the Visini SR model: calc/hazard.py:241, calc/visini.py:247).
    """
    def branch(ind: str, bid: str, body: str, weight) -> list[str]:
        return [
            f'{ind}<logicTreeBranch branchID="{bid}">',
            f"{ind}  <uncertaintyModel><![CDATA[{body}]]></uncertaintyModel>",
            f"{ind}  <uncertaintyWeight>{weight}</uncertaintyWeight>",
            f"{ind}</logicTreeBranch>",
        ]

    def body_of(m: dict) -> str:
        body = f"[{m['class_name']}]"
        params = (m.get("params") or "").strip()
        return body + ("\n" + params if params else "")

    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<nrml xmlns="http://openquake.org/xmlns/nrml/0.4">',
        '  <logicTree logicTreeID="lt_fdha_webgui">',
    ]
    for i, utype in enumerate(["fdhaPrimarySRModel", "fdhaPrimaryFDModel"], 1):
        slot = REGISTRY["slots"][utype]["package"].rsplit(".", 1)[-1]
        parts.append(f'    <logicTreeBranchingLevel branchingLevelID="bl_{i}_{slot}">')
        parts.append(f'      <logicTreeBranchSet branchSetID="bs_{i}_{slot}"'
                     f' uncertaintyType="{utype}">')
        for m in primary[utype]:
            parts += branch("        ", f"{m['class_name'].upper()}_{i}",
                            body_of(m), m["weight"])
        parts += ["      </logicTreeBranchSet>", "    </logicTreeBranchingLevel>"]

    # Level 3: distributed SR — one branch per pair
    parts.append('    <logicTreeBranchingLevel branchingLevelID="bl_3_secondary_surf_rup">')
    parts.append('      <logicTreeBranchSet branchSetID="bs_3_secondary_surf_rup"'
                 ' uncertaintyType="fdhaSecondarySRModel">')
    for k, pr in enumerate(pairs, 1):
        parts += branch("        ", f"PAIR{k}_SSR", body_of(pr["sr"]),
                        pr["weight"])
    parts += ["      </logicTreeBranchSet>", "    </logicTreeBranchingLevel>"]

    # Level 4: distributed FD — per-pair branch set chained to its SR branch
    parts.append('    <logicTreeBranchingLevel branchingLevelID="bl_4_secondary_surf_displ">')
    for k, pr in enumerate(pairs, 1):
        parts.append(f'      <logicTreeBranchSet branchSetID="bs_4_pair{k}"'
                     f' uncertaintyType="fdhaSecondaryFDModel"'
                     f' applyToBranches="PAIR{k}_SSR">')
        parts += branch("        ", f"PAIR{k}_SFD", body_of(pr["fd"]), "1.0")
        parts.append("      </logicTreeBranchSet>")
    parts.append("    </logicTreeBranchingLevel>")
    parts += ["  </logicTree>", "</nrml>"]
    return "\n".join(parts)


def engine_validate(xml_text: str) -> tuple[list, list, str | None]:
    """Validate the logic tree with the engine's own parser/validator."""
    import tempfile
    try:
        from openquake.fdha.logic_tree import nrml_reader, validators
        p = Path(tempfile.mkdtemp()) / "fdha_logic_tree.xml"
        p.write_text(xml_text)
        spec = nrml_reader.parse(p)
        report = validators.validate_spec(spec)
        return list(report.errors), list(report.warnings), None
    except Exception as exc:  # parse failure
        return [], [], str(exc)


SM_LT_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<nrml xmlns:gml="http://www.opengis.net/gml"
      xmlns="http://openquake.org/xmlns/nrml/0.4">
  <logicTree logicTreeID="lt_sm_webgui">
    <logicTreeBranchSet uncertaintyType="sourceModel" branchSetID="bs_sm_webgui">
      <logicTreeBranch branchID="b_sm_webgui">
        <uncertaintyModel>source_model.xml</uncertaintyModel>
        <uncertaintyWeight>1.0</uncertaintyWeight>
      </logicTreeBranch>
    </logicTreeBranchSet>
  </logicTree>
</nrml>
"""


def build_job_ini(cfg: dict) -> str:
    """Render the v5 canonical INI for the configured job (parameter names
    as parsed by openquake/fdha/calc/config_loader.py)."""
    lines = [
        "[general]",
        f"description = {cfg['description']}",
        "calculation_mode = fdha_classical",
        "",
        "[geometry]",
    ]
    if cfg["calc_type"] == "hazard_map":
        lines += [f"region = {cfg['region']}",
                  f"region_grid_spacing = {cfg['grid']}",
                  f"max_distance_km = {cfg['max_dist']}"]
    else:
        lines += [f"sites = {cfg['sites']}"]
    lines += [
        "",
        "[site_params]",
        f"reference_vs30_value = {cfg['vs30']}",
        "",
        "[erf]",
        f"rupture_mesh_spacing = {cfg['mesh']}",
        f"width_of_mfd_bin = {cfg['mfd_bin']}",
        "",
        "[calculation]",
        f"investigation_time = {cfg['investigation_time']}",
        f"displacement_measure_levels = {cfg['dml']}",
        f"r_threshold_km = {cfg['r_threshold_km']}",
        f"near_far_threshold_km = {cfg['near_far_threshold_km']}",
    ]
    if cfg.get("visini_case"):
        lines.append(f"case = {cfg['visini_case']}")
    if cfg["calc_type"] == "hazard_map":
        lines.append(f"return_period = {cfg['return_period']}")
    lines += [
        "fdha_logic_tree_file = fdha_logic_tree.xml",
        "source_model_logic_tree_file = source_model_logic_tree.xml",
        "",
        "[output]",
        "mean = true",
        "quantiles = 0.05 0.16 0.5 0.84 0.95",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Page 1 — Configure
# --------------------------------------------------------------------------
def page_configure() -> None:
    st.header("Configure")

    # ---- Source model ------------------------------------------------------
    st.subheader("Seismic source model")
    col1, col2 = st.columns(2)
    with col1:
        choice = st.selectbox("Source model",
                              list(BUILTIN_SOURCES) + ["Uploaded NRML file…"])
    src_xml: Path | None = None
    geo_defaults = BUILTIN_SOURCES["Norcia Case 3 (IAEA TECDOC-2092)"]
    if choice in BUILTIN_SOURCES:
        geo_defaults = BUILTIN_SOURCES[choice]
        src_xml = geo_defaults["xml"]
    with col2:
        up = st.file_uploader("Upload a NRML source model (XML)", type=["xml"])
        if up is not None:
            updir = HERE / "uploads"
            updir.mkdir(exist_ok=True)
            dest = updir / up.name
            dest.write_bytes(up.getvalue())
            if choice == "Uploaded NRML file…":
                src_xml = dest
    if choice == "Uploaded NRML file…" and src_xml is None:
        st.warning("Upload a source model XML, or pick a built-in one.")
    if src_xml is not None:
        try:
            sources = list_sources(src_xml)
            if sources:
                st.caption(f"`{src_xml.name}` — {len(sources)} fault source(s):")
                st.table(sources)
            else:
                st.error("No fault sources found in this NRML file.")
                src_xml = None
        except Exception as exc:
            st.error(f"Could not parse the source model: {exc}")
            src_xml = None

    # ---- Geometry & calculation parameters ---------------------------------
    st.subheader("Geometry and calculation parameters")
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        calc_type = st.radio(
            "Calculation type",
            ["Hazard curve (sites)", "Hazard map (region)"],
            help="The engine auto-detects map mode from the presence of "
                 "[geometry].region (logic_tree/driver.py:1057-1063).")
        is_map = calc_type.startswith("Hazard map")
        if is_map:
            region = st.text_area("region (lon lat corners)",
                                  geo_defaults["region"], height=68)
            grid = st.number_input("region_grid_spacing [deg]",
                                   min_value=0.001,
                                   value=float(geo_defaults["grid"]),
                                   step=0.005, format="%.3f")
            max_dist = st.number_input("max_distance_km", min_value=1.0,
                                       value=float(geo_defaults["max_dist"]))
            sites = ""
        else:
            sites = st.text_area("sites (lon lat, lon lat, …)",
                                 geo_defaults["sites"], height=68)
            region, grid, max_dist = "", 0.0, 0.0
    with c2:
        # Default 1.0: CalculationConfig, calc/config_loader.py:50
        investigation_time = st.number_input("investigation_time [yr]",
                                             min_value=0.1, value=1.0)
        # Default 0.1: calc/calculators.py:115-117
        r_threshold_km = st.number_input("r_threshold_km", min_value=0.0,
                                         value=0.1, step=0.05, format="%.3f")
        # Default 0.2: calc/calculators.py:123-124
        near_far = st.number_input("near_far_threshold_km", min_value=0.0,
                                   value=0.2, step=0.05, format="%.3f")
    with c3:
        # ERFConfig defaults: calc/config_loader.py:35-36
        mesh = st.number_input("rupture_mesh_spacing [km]", min_value=0.1,
                               value=0.5, step=0.5,
                               help="Coarser spacing runs faster.")
        mfd_bin = st.number_input("width_of_mfd_bin", min_value=0.01,
                                  value=0.1, step=0.05, format="%.2f")
        vs30 = st.number_input("reference_vs30_value [m/s]", min_value=100.0,
                               value=float(geo_defaults["vs30"]))
        return_period = None
        if is_map:
            # Default 100000: calc/hazard_map.py:37
            return_period = st.number_input("return_period [yr]",
                                            min_value=1, value=100000,
                                            step=1000)
    with c4:
        dml = st.text_area("displacement_measure_levels (JSON)", DEFAULT_DML,
                           height=150,
                           help='Format: {"FD": [levels in metres]}')
        try:
            levels = json.loads(dml)["FD"]
            st.caption(f"✓ {len(levels)} displacement levels")
            dml_ok = True
        except Exception as exc:
            st.error(f"Invalid JSON: {exc}")
            dml_ok = False

    # ---- Logic-tree builder -------------------------------------------------
    st.subheader("FDHA logic tree")
    st.caption(
        "Edit model parameters as `key = value` lines — the engine's native "
        "<uncertaintyModel> syntax. Weights within each branch set must sum "
        "to 1.0 (FDLT-001, logic_tree/validators.py:133-143). The default "
        "selection is a light single-branch calculation suitable for a "
        "quick live demonstration."
    )

    def param_editor(meta: dict, key: str, label: str) -> str:
        prefill = meta.get("prefill", "")
        ctor = meta.get("ctor_defaults") or {}
        if ctor and not any(c in prefill for c in ctor):
            extra = "\n".join(f"{k2} = {v2}" for k2, v2 in ctor.items())
            prefill = (prefill + "\n" + extra).strip()
        return st.text_area(label, prefill, height=100, key=key,
                            help="One `key = value` per line; leave empty "
                                 "to use model defaults.")

    def doc_table(meta: dict) -> None:
        dp = meta.get("doc_params") or []
        if dp:
            md = "| param | default | required | allowed |\n|---|---|---|---|\n"
            for r in dp:
                md += (f"| `{r['name']}` | {r['default']} | "
                       f"{'**yes**' if r['required'] else 'no'} | "
                       f"{r['allowed'][:60]} |\n")
            st.markdown(md)
            st.caption("Full reference: docs/UserManual_Enhanced/models/"
                       f"{meta['doc_page']}")
        else:
            st.caption("No documented parameters — the model runs with "
                       "internal defaults.")

    weights_ok = True
    primary: dict = {}
    for utype in ["fdhaPrimarySRModel", "fdhaPrimaryFDModel"]:
        models = REGISTRY["slots"][utype]["models"]
        names = [m["class_name"] for m in models]
        by_name = {m["class_name"]: m for m in models}
        with st.expander(SLOT_LABELS[utype], expanded=True):
            chosen = st.multiselect("Models", names,
                                    default=LIGHT_PRESET[utype],
                                    key=f"ms_{utype}",
                                    label_visibility="collapsed")
            rows = []
            if chosen:
                n = len(chosen)
                eq = [round(1.0 / n, 6)] * (n - 1)
                eq.append(round(1.0 - sum(eq), 6))
                for k, name in enumerate(chosen):
                    meta = by_name[name]
                    wcol, pcol, dcol = st.columns([1, 2, 2])
                    with wcol:
                        w = st.number_input(f"weight — {name}",
                                            min_value=0.0, max_value=1.0,
                                            value=eq[k], step=0.05,
                                            format="%.6f",
                                            key=f"w_{utype}_{name}")
                    with pcol:
                        params = param_editor(meta, f"p_{utype}_{name}",
                                              f"parameters — {name}")
                    with dcol:
                        doc_table(meta)
                    rows.append({"class_name": name, "weight": w,
                                 "params": params})
                total = sum(r["weight"] for r in rows)
                if abs(total - 1.0) <= WEIGHT_TOL:
                    st.success(f"✓ weights sum to {total:.6f}")
                else:
                    st.error(f"✗ weights sum to {total:.6f} — must be "
                             "1.0 ± 1e-6 (FDLT-001)")
                    weights_ok = False
            else:
                st.error("✗ select at least one model")
                weights_ok = False
            primary[utype] = rows

    # Distributed models: locked (SR + FD) pairs, as in the shipped Norcia
    # and Taiwan logic trees. The Visini et al. (2025) FD model runs on a
    # special calculator that requires the Visini SR model
    # (calc/hazard.py:241, calc/visini.py:247), so Visini appears only as
    # a complete pair and cross-combinations are never generated.
    ssr_models = {m["class_name"]: m
                  for m in REGISTRY["slots"]["fdhaSecondarySRModel"]["models"]}
    sfd_models = {m["class_name"]: m
                  for m in REGISTRY["slots"]["fdhaSecondaryFDModel"]["models"]}
    VISINI = {"Visini2025SecondarySR", "Visini2025SecondaryFD"}
    pair_labels = [f"{sr}  +  {fd}"
                   for sr in ssr_models for fd in sfd_models
                   if (sr in VISINI) == (fd in VISINI)]
    default_pair = "Youngs2003SecondarySR  +  Youngs2003SecondaryFD"
    pairs: list = []
    with st.expander("3+4 — Distributed rupture + displacement (locked pairs)",
                     expanded=True):
        st.caption(
            "Distributed SR and FD models are selected as locked pairs and "
            "serialized with `applyToBranches` chaining, mirroring the "
            "published logic trees. Incompatible combinations (e.g. "
            "Visini 2025 displacement on a non-Visini rupture model) are "
            "not offered."
        )
        chosen_pairs = st.multiselect("Pairs", pair_labels,
                                      default=[default_pair],
                                      key="ms_pairs",
                                      label_visibility="collapsed")
        if chosen_pairs:
            n = len(chosen_pairs)
            eq = [round(1.0 / n, 6)] * (n - 1)
            eq.append(round(1.0 - sum(eq), 6))
            for k, lab in enumerate(chosen_pairs):
                sr_name, fd_name = [s.strip() for s in lab.split("+")]
                sr_meta, fd_meta = ssr_models[sr_name], sfd_models[fd_name]
                wcol, pcol1, pcol2 = st.columns([1, 2, 2])
                with wcol:
                    w = st.number_input(f"weight — pair {k + 1}",
                                        min_value=0.0, max_value=1.0,
                                        value=eq[k], step=0.05,
                                        format="%.6f", key=f"w_pair_{lab}")
                with pcol1:
                    sr_params = param_editor(sr_meta, f"p_pair_sr_{lab}",
                                             f"SR parameters — {sr_name}")
                with pcol2:
                    fd_params = param_editor(fd_meta, f"p_pair_fd_{lab}",
                                             f"FD parameters — {fd_name}")
                dc1, dc2 = st.columns(2)
                with dc1:
                    doc_table(sr_meta)
                with dc2:
                    doc_table(fd_meta)
                pairs.append({"weight": w,
                              "sr": {"class_name": sr_name, "params": sr_params},
                              "fd": {"class_name": fd_name, "params": fd_params}})
            total = sum(p["weight"] for p in pairs)
            if abs(total - 1.0) <= WEIGHT_TOL:
                st.success(f"✓ pair weights sum to {total:.6f}")
            else:
                st.error(f"✗ pair weights sum to {total:.6f} — must be "
                         "1.0 ± 1e-6 (FDLT-001)")
                weights_ok = False
        else:
            st.error("✗ select at least one (SR + FD) pair")
            weights_ok = False

    # Visini et al. (2025) job-level 'case' parameter ([calculation].case,
    # cf. job_norcia_case3_iaea_curve.ini:18 and the model docs, which mark
    # it Required). case3 = Combination A only — the configuration used by
    # the shipped Norcia benchmark.
    visini_case = None
    if any("Visini" in p["sr"]["class_name"] for p in pairs):
        visini_case = st.selectbox(
            "Visini et al. (2025) combination case ([calculation].case)",
            ["case3", "case2", "case1"],
            help="Case 3 → combination A only; Case 2 → A/B; Case 1 → "
                 "A/B/C. Note: the combination-C path (case1) currently "
                 "raises an error in the engine (visini.py:305 calls "
                 "get_prob without the required style/pixel_size "
                 "arguments) — prefer case2/case3 until fixed upstream.")

    # ---- Live engine validation + preview ------------------------------------
    lt_xml = build_fdha_lt_xml(primary, pairs) if weights_ok else None
    engine_ok = False
    if lt_xml:
        errors, warnings, parse_err = engine_validate(lt_xml)
        if parse_err:
            st.error(f"Logic tree does not parse: {parse_err}")
        elif errors:
            for e in errors:
                st.error(f"{e.code}: {e.message}")
        else:
            engine_ok = True
            msg = "Logic tree validated by the engine (nrml_reader + validate_spec)"
            if warnings:
                st.warning(msg + " with warnings:\n" +
                           "\n".join(f"- {w.code}: {w.message}" for w in warnings))
            else:
                st.success("✓ " + msg)
    n_branches = (max(len(primary["fdhaPrimarySRModel"]), 1)
                  * max(len(primary["fdhaPrimaryFDModel"]), 1)
                  * max(len(pairs), 1))
    st.caption(f"Full enumeration: **{n_branches} end-branch(es)**. "
               "Runtime grows linearly with branches × sites; keep it small "
               "for a live demonstration.")
    with st.expander("Preview: fdha_logic_tree.xml"):
        if lt_xml:
            st.code(lt_xml, language="xml")
            st.download_button("⬇ fdha_logic_tree.xml", lt_xml,
                               file_name="fdha_logic_tree.xml")
        else:
            st.warning("Fix the weight errors above to generate the XML.")

    st.session_state["config"] = {
        "description": f"webgui job ({choice})",
        "source_label": choice,
        "source_xml": str(src_xml) if src_xml else None,
        "calc_type": "hazard_map" if is_map else "hazard_curve",
        "sites": sites.replace("\n", " ").strip(),
        "region": region.replace("\n", " ").strip(),
        "grid": grid, "max_dist": max_dist, "vs30": vs30,
        "mesh": mesh, "mfd_bin": mfd_bin,
        "investigation_time": investigation_time,
        "r_threshold_km": r_threshold_km,
        "near_far_threshold_km": near_far,
        "return_period": return_period,
        "dml": dml.replace("\n", " ").strip(),
        "primary": primary,
        "pairs": pairs,
        "visini_case": visini_case,
        "n_branches": n_branches,
        "valid": bool(weights_ok and engine_ok and dml_ok and src_xml),
        "lt_xml": lt_xml,
    }


# --------------------------------------------------------------------------
# Page 2 — Run (real calculation)
# --------------------------------------------------------------------------
def page_run() -> None:
    st.header("Run")
    cfg = st.session_state.get("config")
    if cfg is None:
        st.warning("No configuration yet — visit **1 · Configure** first.")
        return

    st.subheader("Job summary")
    c1, c2, c3 = st.columns(3)
    c1.metric("Source model", cfg["source_label"].split(" (")[0])
    c1.metric("Calculation type", cfg["calc_type"].replace("_", " "))
    c2.metric("End-branches", cfg["n_branches"])
    c2.metric("r_threshold_km", f'{cfg["r_threshold_km"]} km')
    c3.metric("rupture_mesh_spacing", f'{cfg["mesh"]} km')
    if cfg["return_period"]:
        c3.metric("return_period", f'{cfg["return_period"]} yr')
    with st.expander("job.ini to be executed"):
        st.code(build_job_ini(cfg), language="ini")

    if not cfg["valid"]:
        st.error("Configuration is incomplete or invalid — fix the issues "
                 "flagged on **1 · Configure** before running.")
        return

    est = cfg["n_branches"]
    if est > 8:
        st.warning(f"{est} end-branches — this is a full calculation, not a "
                   "quick demo; it may take many minutes.")

    if st.button("▶ Run calculation", type="primary"):
        stamp = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
        jobdir = RUNS / f"run_{stamp}"
        outdir = jobdir / "out"
        jobdir.mkdir(parents=True, exist_ok=True)
        shutil.copy(cfg["source_xml"], jobdir / "source_model.xml")
        (jobdir / "source_model_logic_tree.xml").write_text(SM_LT_TEMPLATE)
        (jobdir / "fdha_logic_tree.xml").write_text(cfg["lt_xml"])
        ini = jobdir / "job.ini"
        ini.write_text(build_job_ini(cfg))

        log_buf = io.StringIO()
        handler = logging.StreamHandler(log_buf)
        handler.setLevel(logging.INFO)
        logging.getLogger().addHandler(handler)
        t0 = _dt.datetime.now()
        try:
            with st.status("Running the oq-pfdha engine…", expanded=True) as status:
                st.write(f"Job directory: `{jobdir}`")
                from openquake.fdha.logic_tree.driver import FdhaLogicTree
                result = FdhaLogicTree.from_ini(ini).run(outdir=outdir)
                dt = (_dt.datetime.now() - t0).total_seconds()
                status.update(label=f"Completed in {dt:.1f} s",
                              state="complete")
            st.session_state["last_run"] = {
                "outdir": str(outdir), "jobdir": str(jobdir),
                "mode": result.mode, "elapsed_s": dt,
            }
            st.success(f"Calculation finished ({result.mode}, {dt:.1f} s) — "
                       "see **3 · Results**.")
        except Exception:
            st.error("The engine raised an error — full traceback below.")
            st.exception(Exception("engine failure"))
            import traceback
            st.code(traceback.format_exc())
        finally:
            logging.getLogger().removeHandler(handler)
        log_text = log_buf.getvalue().strip()
        if log_text:
            with st.expander("Engine log"):
                st.code(log_text[-8000:])


# --------------------------------------------------------------------------
# Page 3 — Results (from the last real run)
# --------------------------------------------------------------------------
def page_results() -> None:
    st.header("Results")
    run = st.session_state.get("last_run")
    if not run:
        st.warning("No completed run in this session — execute one on "
                   "**2 · Run** first.")
        return
    outdir = Path(run["outdir"])
    st.caption(f"Run output: `{outdir}` — mode **{run['mode']}**, "
               f"{run['elapsed_s']:.1f} s")

    import pandas as pd

    if run["mode"] == "hazard_curve":
        agg = outdir / "aggregate_hazard.csv"
        if not agg.exists():
            st.error(f"Expected output not found: {agg}")
            return
        df = pd.read_csv(agg, comment="#")
        st.subheader("Hazard curves (weighted mean + fractiles)")
        site_ids = sorted(df["site_id"].unique())
        chosen = st.selectbox(
            "Site", site_ids,
            format_func=lambda s: (
                f"site {s} ({df[df.site_id == s].lon.iloc[0]:.3f}, "
                f"{df[df.site_id == s].lat.iloc[0]:.3f})"))
        d = df[df["site_id"] == chosen]

        import plotly.graph_objects as go
        fig = go.Figure()
        if "quantile-0.84" in d:
            fig.add_trace(go.Scatter(x=d["D0"], y=d["quantile-0.84"],
                                     line=dict(width=0), showlegend=False,
                                     hoverinfo="skip"))
            fig.add_trace(go.Scatter(x=d["D0"], y=d["quantile-0.16"],
                                     fill="tonexty",
                                     fillcolor="rgba(170,51,119,0.15)",
                                     line=dict(width=0),
                                     name="16–84% fractiles"))
        # per-branch spaghetti
        branch_dir = outdir / "hazard_curves"
        branch_files = sorted(branch_dir.glob("branch_*.csv"))
        if len(branch_files) > 1 and st.checkbox(
                f"Show all {len(branch_files)} branch curves", value=True):
            for bf in branch_files:
                b = pd.read_csv(bf, comment="#")
                b = b[b["site_id"] == chosen]
                fig.add_trace(go.Scatter(x=b["D0"], y=b["annual_rate"],
                                         line=dict(color="#bbbbbb", width=0.8),
                                         showlegend=False, hoverinfo="skip"))
        fig.add_trace(go.Scatter(x=d["D0"], y=d["mean"], name="weighted mean",
                                 line=dict(color="#AA3377", width=3.5)))
        fig.update_xaxes(type="log", title="Displacement (m)")
        fig.update_yaxes(type="log", title="Annual rate of exceedance (1/yr)")
        fig.update_layout(height=500, margin=dict(t=10),
                          legend=dict(orientation="h", y=-0.25))
        st.plotly_chart(fig, use_container_width=True)
        st.download_button("⬇ aggregate_hazard.csv", agg.read_bytes(),
                           file_name="aggregate_hazard.csv", mime="text/csv")
    else:
        st.subheader("Displacement hazard map")
        agg_dir = outdir / "aggregate"
        mean_csv = agg_dir / "displacement_map_mean.csv"
        if not mean_csv.exists():
            st.error(f"Expected output not found: {mean_csv}")
            return
        layers = ["mean"] + sorted(
            p.stem.replace("displacement_map_", "")
            for p in agg_dir.glob("displacement_map_quantile-*.csv"))
        which = st.radio("Layer", layers, horizontal=True)
        m = pd.read_csv(agg_dir / f"displacement_map_{which}.csv", comment="#")
        col = [c for c in m.columns if c.startswith("displ")][0]
        import numpy as np
        import pydeck as pdk
        pos = m[m[col] > 0].copy()
        if pos.empty:
            st.info("All displacement values are zero for this layer.")
            return
        lo, hi = np.log10(pos[col].min()), np.log10(pos[col].max())
        t = (np.log10(pos[col]) - lo) / max(hi - lo, 1e-12)
        pos["color"] = [[int(40 + 215 * x), int(60 * (1 - x)),
                         int(140 * (1 - x)), 200] for x in t]
        view = pdk.ViewState(latitude=float(pos.lat.mean()),
                             longitude=float(pos.lon.mean()), zoom=9.5)
        st.pydeck_chart(pdk.Deck(
            layers=[pdk.Layer("ScatterplotLayer", data=pos,
                              get_position=["lon", "lat"],
                              get_fill_color="color", get_radius=150,
                              pickable=True)],
            initial_view_state=view,
            tooltip={"text": f"{col}: {{{col}}} m"}, map_style=None))
        st.download_button(f"⬇ displacement_map_{which}.csv",
                           (agg_dir / f"displacement_map_{which}.csv").read_bytes(),
                           file_name=f"displacement_map_{which}.csv",
                           mime="text/csv")

    # ---- Diagnostics & full download -----------------------------------------
    st.subheader("Diagnostics")
    for rep in sorted(outdir.glob("source_model_branches/*/validator_report.txt")):
        with st.expander(f"Validator report — {rep.parent.name}"):
            st.code(rep.read_text())
    manifest = outdir / "manifest.json"
    if manifest.exists():
        with st.expander("manifest.json (branches, weights, outputs)"):
            st.json(json.loads(manifest.read_text()))

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in outdir.rglob("*"):
            if f.is_file():
                zf.write(f, f.relative_to(outdir.parent))
    st.download_button("⬇ Download complete output directory (ZIP)",
                       buf.getvalue(), file_name=f"{outdir.parent.name}.zip",
                       mime="application/zip")


# --------------------------------------------------------------------------
# Navigation + footer
# --------------------------------------------------------------------------
st.sidebar.title("oq-pfdha GUI")
page = st.sidebar.radio("Navigation", ["1 · Configure", "2 · Run", "3 · Results"])
st.sidebar.info(
    "This interface assembles a real oq-pfdha job and runs the actual "
    "engine. The default configuration is a **light single-branch "
    "calculation** that completes in under a minute — ideal for live "
    "demonstrations."
)

if page.startswith("1"):
    page_configure()
elif page.startswith("2"):
    page_run()
else:
    page_results()

st.divider()
st.markdown(
    "<div style='text-align:center; color:#888; font-size:0.85em; "
    "line-height:1.7'>"
    "<b>oq-pfdha</b> — Probabilistic Fault Displacement Hazard Analysis · "
    "GNU AGPL v3.0-or-later<br>"
    "Cite: Chen, Y.-S. (2025). <i>openquake.fdha: Python tools for "
    "probabilistic fault displacement hazard analysis</i> (v1.0.0) "
    "[Software]. OGS. "
    "<a href='https://github.com/vup1120/oq-pfdha'>github.com/vup1120/oq-pfdha</a>"
    " (CITATION.cff)<br>"
    "<b>Prototype interface</b> — review configurations and verify results "
    "independently before use in production hazard assessment."
    "</div>",
    unsafe_allow_html=True,
)
