"""oq-pfdha web GUI - prototype front-end (Streamlit).

A working web interface for Probabilistic Fault Displacement Hazard
Analysis: it assembles a real job (INI + NRML source-model logic tree +
NRML FDHA logic tree) from the form inputs and executes the actual
oq-pfdha engine (`FdhaLogicTree.from_ini(...).run(...)`) - the same code
path as the `fdha` command line.

Model lists and per-model parameter documentation come from registry.json,
a snapshot of the actual model registry and User-Manual parameter tables
generated by generate_registry.py.

Requires the oq-pfdha package installed (pip install -e . at the repo
root) plus webgui_demo/requirements.txt.

Run:  streamlit run webgui_demo/app.py
"""
from __future__ import annotations

import datetime as _dt
import base64
import io
import json
import logging
import os
import shutil
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path

import streamlit as st

HERE = Path(__file__).parent
REPO = HERE.parent
RUNS = HERE / "runs"
REGISTRY = json.loads((HERE / "registry.json").read_text())
PLATFORM_ICON = HERE / "assets" / "platform_icon.png"

os.environ.setdefault("NUMBA_CACHE_DIR", str(Path("/tmp") / "oq_pfdha_numba"))
os.environ.setdefault("MPLCONFIGDIR", str(Path("/tmp") / "oq_pfdha_matplotlib"))

# Display order/labels for the four logic-tree slots
# (uncertaintyType values from openquake/fdha/logic_tree/types.py:7-12).
SLOT_LABELS = {
    "fdhaPrimarySRModel": "1 - Principal surface rupture (probability)",
    "fdhaPrimaryFDModel": "2 - Principal fault displacement",
    "fdhaSecondarySRModel": "3 - Distributed surface rupture (probability)",
    "fdhaSecondaryFDModel": "4 - Distributed fault displacement",
}

# Light-calculation default: the Youngs-2003 chain of the Norcia Case 3
# benchmark logic tree (config_norcia_case3_iaea_fdha_logic_tree.xml) -
# a single end-branch that completes in well under a minute.
LIGHT_PRESET = {
    "fdhaPrimarySRModel": ["Youngs2003PrimarySR"],
    "fdhaPrimaryFDModel": ["Youngs2003PrimaryFD"],
    "fdhaSecondarySRModel": ["Youngs2003SecondarySR"],
    "fdhaSecondaryFDModel": ["Youngs2003SecondaryFD"],
}

# Built-in source models shipped with the repository. Geometry defaults are
# the ones used by the corresponding in-repo jobs.
BUILTIN_SOURCES = {
    "Norcia Case 3 (IAEA TECDOC-2092)": {
        "xml": REPO / "openquake/fdha/test/benchmark/norcia_case3_iaea/source_model_norcia_case3.xml",
        # job_norcia_case3_iaea_curve.ini:6 / _map.ini:6-8
        "sites": "13.278 42.767, 13.188 42.749, 13.212 42.853",
        "region": "13.05 42.65, 13.35 42.65, 13.35 42.95, 13.05 42.95",
        "grid": 0.005, "max_dist": 50.0, "vs30": 760.0,
    },
    "Minimal example (single simple fault)": {
        "xml": REPO / "examples/source_model.xml",
        # examples/hazard_curve_minimal.ini:6
        "sites": "16.16573727 39.64704451",
        "region": "16.0 39.5, 16.35 39.5, 16.35 39.8, 16.0 39.8",
        "grid": 0.01, "max_dist": 50.0, "vs30": 760.0,
    },
}

# Default displacement levels: job_norcia_case3_iaea_curve.ini:17
DEFAULT_DML = ('{"FD": [0.0001, 0.001, 0.005, 0.01, 0.015, 0.03, 0.05, '
               '0.075, 0.1, 0.15, 0.3, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, '
               '5.0, 7.5, 10.0]}')

# Weight tolerance mirrors validator rule FDLT-001
# (openquake/fdha/logic_tree/validators.py:133-143).
WEIGHT_TOL = 1e-6

st.set_page_config(
    page_title="oq-pfdha GUI",
    page_icon=PLATFORM_ICON if PLATFORM_ICON.exists() else None,
    layout="wide",
)

# --------------------------------------------------------------------------
# oq-pfdha design system tokens, ported from the June 2026 handoff for
# Streamlit. The source design system is React/CSS; these constants preserve
# its brand palette, typography, rounded controls and warm scientific tone.
# --------------------------------------------------------------------------
BRAND = "#1b2c4b"
BRAND_DARK = "#142138"
BRAND_DEEP = "#0e1727"
ACCENT = "#f2762b"
ACCENT_DARK = "#db5f14"
BLUE = "#3b82f6"
SAGE = "#6f8140"
OCHRE = "#c2891c"
BRICK = "#c5402c"
PAPER = "#faf8f3"
CLAY_50 = "#faf7f2"
CLAY_100 = "#f3eee6"
CLAY_150 = "#ebe4d9"
CLAY_200 = "#e0d7c8"
CLAY_500 = "#877560"
CLAY_600 = "#655647"
CLAY_800 = "#352d24"

def image_data_uri(path: Path) -> str:
    """Return a PNG data URI for small local brand assets."""
    return "data:image/png;base64," + base64.b64encode(path.read_bytes()).decode()


PLATFORM_ICON_URI = image_data_uri(PLATFORM_ICON) if PLATFORM_ICON.exists() else ""
LOGO_MARK = f"<img class='pfdha-logo' src='{PLATFORM_ICON_URI}' alt='oq-pfdha'>" if PLATFORM_ICON_URI else ""

st.markdown(f"""
<style>
@import url('https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400..800&family=Hanken+Grotesk:ital,wght@0,400..800;1,400..600&family=JetBrains+Mono:ital,wght@0,400..700;1,400..600&display=swap');

:root {{
    --font-display: 'Bricolage Grotesque', 'Hanken Grotesk', system-ui, sans-serif;
    --font-sans: 'Hanken Grotesk', system-ui, -apple-system, 'Segoe UI', sans-serif;
    --font-mono: 'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, monospace;
    --brand: {BRAND};
    --brand-dark: {BRAND_DARK};
    --brand-deep: {BRAND_DEEP};
    --accent: {ACCENT};
    --accent-dark: {ACCENT_DARK};
    --paper: {PAPER};
    --clay-50: {CLAY_50};
    --clay-100: {CLAY_100};
    --clay-150: {CLAY_150};
    --clay-200: {CLAY_200};
    --clay-500: {CLAY_500};
    --clay-600: {CLAY_600};
    --clay-800: {CLAY_800};
    --radius-md: 12px;
    --radius-lg: 16px;
    --shadow-sm: 0 2px 6px rgba(61, 45, 32, 0.08);
    --shadow-md: 0 6px 18px rgba(61, 45, 32, 0.10);
    --ring: 0 0 0 3px rgba(242, 118, 43, 0.28);
}}

/* ---- Base typography and page shell ---- */
html, body, [data-testid="stAppViewContainer"] {{
    font-family: var(--font-sans);
}}
[data-testid="stAppViewContainer"] p,
[data-testid="stAppViewContainer"] label,
[data-testid="stAppViewContainer"] input,
[data-testid="stAppViewContainer"] textarea,
[data-testid="stAppViewContainer"] button,
[data-testid="stAppViewContainer"] table {{
    font-family: var(--font-sans);
}}
[data-testid="stAppViewContainer"] {{
    background:
        repeating-linear-gradient(0deg, transparent 0 31px, rgba(194, 137, 28, 0.045) 31px 32px),
        var(--paper);
}}
.block-container {{
    max-width: 1180px;
    padding-top: 2rem;
    padding-bottom: 4rem;
}}
[data-testid="stAppViewContainer"] .stMarkdown p,
[data-testid="stAppViewContainer"] .stMarkdown li {{
    font-size: 1rem; line-height: 1.6; color: var(--clay-800);
}}
[data-testid="stCaptionContainer"] p {{
    color: var(--clay-600) !important;
    font-size: 0.88rem !important;
}}
[data-testid="stWidgetLabel"] p {{
    color: var(--brand);
    font-size: 0.96rem !important;
    font-weight: 650;
}}
[data-testid="stRadio"] label p,
[data-testid="stCheckbox"] label p {{
    font-size: 0.96rem !important;
}}

/* ---- Headings and product masthead ---- */
h1, h2, h3 {{
    color: var(--brand);
    font-family: var(--font-display);
    letter-spacing: -0.01em;
}}
h1 {{
    font-size: 2.35rem !important;
    font-weight: 760;
}}
h2 {{
    border-bottom: 2px solid var(--accent);
    font-size: 1.75rem !important;
    font-weight: 700;
    margin-top: 0.4rem;
    padding-bottom: 0.35rem;
}}
h3 {{
    color: var(--brand);
    font-size: 1.28rem !important;
    font-weight: 650;
    margin-top: 1.2rem;
}}
.pfdha-band {{
    align-items: center;
    background:
        linear-gradient(90deg, rgba(242, 118, 43, 0.10), transparent 40%),
        #fff;
    border: 1px solid var(--clay-150);
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow-md);
    display: flex;
    gap: 1rem;
    margin-bottom: 1.35rem;
    overflow: hidden;
    padding: 1rem 1.15rem;
    position: relative;
}}
.pfdha-band::after {{
    background: var(--accent);
    bottom: 0;
    content: "";
    height: 4px;
    left: 0;
    position: absolute;
    right: 0;
}}
.pfdha-band .t {{
    color: var(--brand);
    font-family: var(--font-display);
    font-size: 2rem;
    font-weight: 760;
    line-height: 1.05;
}}
.pfdha-logo {{
    border-radius: 13px;
    box-shadow: 0 10px 24px rgba(14, 23, 39, 0.18);
    flex: 0 0 auto;
    height: 44px;
    object-fit: cover;
    width: 44px;
}}
.pfdha-band .s {{
    color: var(--clay-600);
    font-size: 1rem;
    margin-top: 0.15rem;
}}
.pfdha-badge {{
    background: #fcf3da;
    border: 1px solid #f2d177;
    border-radius: 999px;
    color: #785212;
    font-family: var(--font-mono);
    font-size: 0.72rem;
    font-weight: 650;
    margin-left: auto;
    padding: 0.38rem 0.62rem;
    text-transform: uppercase;
}}

/* ---- Sidebar: dark brand rail from the handoff ---- */
section[data-testid="stSidebar"] {{
    background: var(--brand);
    border-right: 1px solid rgba(255,255,255,0.08);
}}
section[data-testid="stSidebar"] > div:first-child {{
    padding-top: 1.25rem;
}}
section[data-testid="stSidebar"] [data-testid="stRadio"] label p {{
    color: #e0d7c8;
    font-weight: 650;
}}
section[data-testid="stSidebar"] [data-testid="stRadio"] label:hover p {{
    color: #fff;
}}
section[data-testid="stSidebar"] [data-testid="stWidgetLabel"] p {{
    color: #cabca6;
    font-family: var(--font-mono);
    font-size: 0.74rem !important;
    letter-spacing: 0.08em;
    text-transform: uppercase;
}}
.pfdha-side-brand {{
    align-items: center;
    display: flex;
    gap: 0.75rem;
    margin: 0 0 1.25rem;
}}
.pfdha-side-brand .pfdha-logo {{
    height: 42px;
    width: 42px;
}}
.pfdha-side-brand .t {{
    color: #fff;
    font-family: var(--font-display);
    font-size: 1.38rem;
    font-weight: 760;
    line-height: 1;
}}
.pfdha-side-brand .s {{
    color: #cabca6;
    font-family: var(--font-mono);
    font-size: 0.57rem;
    letter-spacing: 0.12em;
    margin-top: 0.25rem;
    text-transform: uppercase;
}}
.pfdha-side-note {{
    background: rgba(255,255,255,0.055);
    border: 1px solid rgba(255,255,255,0.09);
    border-radius: var(--radius-md);
    color: #e0d7c8;
    font-size: 0.84rem;
    line-height: 1.5;
    margin-top: 1rem;
    padding: 0.85rem 0.9rem;
}}
.pfdha-side-note b {{
    color: #fff;
}}

/* ---- Controls ---- */
.stButton button, .stDownloadButton button, .stFormSubmitButton button {{
    border: 1.5px solid var(--accent);
    border-radius: 999px;
    color: var(--accent-dark);
    font-weight: 650;
    transition: transform 120ms ease, box-shadow 120ms ease, background 120ms ease;
}}
.stButton button:hover, .stDownloadButton button:hover,
.stFormSubmitButton button:hover {{
    background: var(--accent);
    border-color: var(--accent);
    box-shadow: var(--shadow-sm);
    color: #fff;
    transform: translateY(-1px);
}}
.stButton button[kind="primary"] {{
    background: var(--brand);
    border-color: var(--brand);
    color: #fff;
}}
.stButton button[kind="primary"]:hover {{
    background: var(--accent);
    border-color: var(--accent);
}}
button:focus-visible, input:focus-visible, textarea:focus-visible {{
    box-shadow: var(--ring) !important;
}}

/* ---- Cards, tables, code and feedback ---- */
[data-testid="stExpander"] {{
    background: #fff;
    border: 1px solid var(--clay-150);
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow-sm);
}}
[data-testid="stExpander"] summary p {{
    color: var(--brand);
    font-weight: 650;
}}
[data-testid="stExpander"] summary [data-testid="stIconMaterial"],
[data-testid="stExpander"] summary span:has(> span[data-testid="stIconMaterial"]) {{
    display: none !important;
}}
[data-testid="stTable"] td, [data-testid="stTable"] th,
[data-testid="stDataFrame"] {{
    font-size: 0.94rem;
}}
code, pre, [data-testid="stCodeBlock"] * {{
    font-family: var(--font-mono) !important;
}}
code {{
    background: var(--clay-100);
    border: 1px solid var(--clay-150);
    border-radius: 6px;
    color: var(--brand);
    font-size: 0.88em;
    padding: 0.1rem 0.25rem;
}}
[data-testid="stMetric"] {{
    background: #fff;
    border: 1px solid var(--clay-150);
    border-radius: var(--radius-md);
    box-shadow: var(--shadow-sm);
    padding: 0.85rem 0.9rem;
}}
[data-testid="stMetricLabel"] p {{
    color: var(--clay-600);
    font-family: var(--font-mono);
    font-size: 0.75rem !important;
}}
[data-testid="stMetricValue"] {{
    color: var(--brand);
    font-family: var(--font-display);
}}
[data-testid="stAlert"] {{
    border-radius: var(--radius-md);
    border-width: 1px;
}}
textarea, input, [data-baseweb="select"] > div {{
    border-radius: 12px !important;
}}
hr {{
    border-color: var(--clay-150);
}}
a {{
    color: {BLUE};
}}
a:hover {{
    color: var(--accent-dark);
}}

/* Hide Streamlit chrome for a cleaner product surface */
#MainMenu {{ visibility: hidden; }}
header[data-testid="stHeader"] {{ background: transparent; }}
</style>
""", unsafe_allow_html=True)

st.markdown(
    "<div class='pfdha-band'>"
    f"{LOGO_MARK}"
    "<div><div class='t'>oq-pfdha</div>"
    "<div class='s'>Probabilistic Fault Displacement Hazard Analysis - "
    "web interface</div></div>"
    "<div class='pfdha-badge'>Prototype interface</div>"
    "</div>",
    unsafe_allow_html=True,
)


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------
def list_sources(xml_path: Path) -> list[dict]:
    """Parse an NRML source model and list its fault sources (id/name/rake)."""
    ns = {"n": "http://openquake.org/xmlns/nrml/0.4",
          "n5": "http://openquake.org/xmlns/nrml/0.5"}
    root = ET.parse(xml_path).getroot()
    out = []
    for elem in root.iter():
        tag = elem.tag.split("}")[-1]
        if tag.endswith("FaultSource"):
            rake_el = elem.find(".//n:rake", ns) or elem.find(".//n5:rake", ns)
            rake = float(rake_el.text) if rake_el is not None else None
            style = ""
            if rake is not None:
                # rake -> style classification convention used by the engine
                if -135 <= rake <= -45:
                    style = "normal"
                elif 45 <= rake <= 135:
                    style = "reverse"
                else:
                    style = "strike-slip"
            out.append({"id": elem.get("id"), "name": elem.get("name"),
                        "type": tag, "rake": rake, "style": style})
    return out


# Distributed model families the engine requires to co-occur in a branch:
# the Visini et al. (2025) models run on a special calculator dispatched
# when EITHER distributed slot is Visini (calc/hazard.py:241), which needs
# the Visini SR's get_prob_slice (calc/visini.py:247) and the Visini FD's
# extended get_prob signature (calc/visini.py:320-329). Extend this list if
# future coupled model families are added.
COUPLED_DISTRIBUTED = [("Visini2025SecondarySR", "Visini2025SecondaryFD")]
COUPLED_SR_TO_FD = dict(COUPLED_DISTRIBUTED)
COUPLED_FD_TO_SR = {fd: sr for sr, fd in COUPLED_DISTRIBUTED}

# Model families whose calibrated faulting mechanism differs from some
# source styles, checked against the engine-enumerated end-branches so the
# user is informed in Configure instead of hitting a deep traceback.
#   intended : source mechanisms the model is calibrated for
#   kind     : "warn"  -> advisory only, run still allowed
#              "block" -> the engine cannot run this pairing, run prevented
# NB: for Youngs2003 the `style` parameter is the WC1994 coefficient-dataset
# selector ("all"/"normal"), NOT the source mechanism - the model is a
# normal-faulting model, so reverse/strike-slip sources get an advisory.
STYLE_CONSTRAINTS = [
    {"prefix": "Youngs2003", "intended": {"normal"}, "kind": "warn",
     "message": (
         "Youngs et al. (2003) is a **normal-faulting** model. Its `style` "
         "parameter only selects the coefficient dataset (`all` = "
         "Wells & Coppersmith 1994 all-styles, `normal` = normal-only) and "
         "does not extend the model to other mechanisms. This pairing is "
         "outside the model's calibrated range - set `style = all` or "
         "`style = normal` explicitly to run, and interpret the result with "
         "caution.")},
    {"prefix": "Chiou2025", "intended": {"strike-slip"}, "kind": "block",
     "message": ("Chiou et al. (2025) is a strike-slip model and cannot run "
                 "on this source (primary_surf_displ/chiou2025.py:106).")},
    {"prefix": "Visini2025", "intended": {"normal", "reverse"},
     "kind": "block",
     "message": ("Visini et al. (2025) is a dip-slip (normal/reverse) model "
                 "and cannot run on a strike-slip source.")},
]


def style_fig(fig, height: int = 560) -> None:
    """Publication-style plot formatting (large fonts, framed axes,
    power-of-ten tick labels)."""
    fig.update_layout(
        template="simple_white", height=height,
        paper_bgcolor="#ffffff",
        plot_bgcolor="#ffffff",
        font=dict(family="Hanken Grotesk, Helvetica, Arial, sans-serif",
                  size=17, color=CLAY_800),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, x=0,
                    font=dict(size=16)),
        margin=dict(t=40, r=25, b=15, l=15),
        hoverlabel=dict(font_size=15),
    )
    axis_kw = dict(
        title_font=dict(size=20), tickfont=dict(size=16),
        showline=True, linewidth=1.6, linecolor=BRAND, mirror=True,
        ticks="outside", tickwidth=1.4, ticklen=7,
        showgrid=True, gridcolor="rgba(194,137,28,0.16)",
        exponentformat="power",
        minor=dict(showgrid=True, gridcolor="rgba(194,137,28,0.07)",
                   ticks="outside", ticklen=4),
    )
    fig.update_xaxes(**axis_kw)
    fig.update_yaxes(**axis_kw)


def build_fdha_lt_xml(selections: dict) -> str:
    """Serialize the 4-slot selection to one NRML logic-tree XML (schema per
    openquake/fdha/logic_tree/nrml_reader.py:24-56).

    All four slots are presented to the user as independent choices. Levels
    1-3 serialize as plain branch sets. At level 4, engine-coupled FD models
    (COUPLED_DISTRIBUTED) are chained to their SR partner with
    applyToBranches, and the remaining FD models are chained to the
    remaining SR branches - applyToBranches matches by set intersection
    (enumerator.py:81-84), so one branch set serves many parents. With no
    coupled model selected the tree is fully flat.
    """
    def branch(ind: str, bid: str, m: dict, weight) -> list[str]:
        body = f"[{m['class_name']}]"
        params = (m.get("params") or "").strip()
        if params:
            body += "\n" + params
        return [
            f'{ind}<logicTreeBranch branchID="{bid}">',
            f"{ind}  <uncertaintyModel><![CDATA[{body}]]></uncertaintyModel>",
            f"{ind}  <uncertaintyWeight>{weight}</uncertaintyWeight>",
            f"{ind}</logicTreeBranch>",
        ]

    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<nrml xmlns="http://openquake.org/xmlns/nrml/0.4">',
        '  <logicTree logicTreeID="lt_fdha_webgui">',
    ]
    # Branch IDs embed the row index so the same model can appear in several
    # branches (with different parameters) without colliding.
    def slot_bids(utype: str, level: int) -> list[str]:
        return [f"{m['class_name'].upper()}_{level}_{j}"
                for j, m in enumerate(selections[utype])]

    plain_levels = ["fdhaPrimarySRModel", "fdhaPrimaryFDModel",
                    "fdhaSecondarySRModel"]
    for i, utype in enumerate(plain_levels, 1):
        slot = REGISTRY["slots"][utype]["package"].rsplit(".", 1)[-1]
        parts.append(f'    <logicTreeBranchingLevel branchingLevelID="bl_{i}_{slot}">')
        parts.append(f'      <logicTreeBranchSet branchSetID="bs_{i}_{slot}"'
                     f' uncertaintyType="{utype}">')
        for bid, m in zip(slot_bids(utype, i), selections[utype]):
            parts += branch("        ", bid, m, m["weight"])
        parts += ["      </logicTreeBranchSet>", "    </logicTreeBranchingLevel>"]

    ssr = selections["fdhaSecondarySRModel"]
    sfd = selections["fdhaSecondaryFDModel"]
    ssr_bids = slot_bids("fdhaSecondarySRModel", 3)
    fd_bids = slot_bids("fdhaSecondaryFDModel", 4)
    free_fd = [(bid, m) for bid, m in zip(fd_bids, sfd)
               if m["class_name"] not in COUPLED_FD_TO_SR]
    coupled_fd = [(bid, m) for bid, m in zip(fd_bids, sfd)
                  if m["class_name"] in COUPLED_FD_TO_SR]
    free_sr_ids = [bid for bid, m in zip(ssr_bids, ssr)
                   if m["class_name"] not in COUPLED_SR_TO_FD]
    # First branch id seen for each coupled SR class, used to chain its
    # FD partner via applyToBranches.
    sr_id_by_class: dict = {}
    for bid, m in zip(ssr_bids, ssr):
        sr_id_by_class.setdefault(m["class_name"], bid)

    parts.append('    <logicTreeBranchingLevel branchingLevelID="bl_4_secondary_surf_displ">')
    if free_fd:
        cond = (f' applyToBranches="{" ".join(free_sr_ids)}"'
                if coupled_fd else "")
        parts.append('      <logicTreeBranchSet branchSetID="bs_4_secondary_surf_displ"'
                     f' uncertaintyType="fdhaSecondaryFDModel"{cond}>')
        for bid, m in free_fd:
            parts += branch("        ", bid, m, m["weight"])
        parts.append("      </logicTreeBranchSet>")
    for j, (bid, m) in enumerate(coupled_fd):
        sr_id = sr_id_by_class.get(COUPLED_FD_TO_SR[m["class_name"]], "")
        parts.append(f'      <logicTreeBranchSet branchSetID="bs_4_{m["class_name"].lower()}_{j}"'
                     f' uncertaintyType="fdhaSecondaryFDModel"'
                     f' applyToBranches="{sr_id}">')
        parts += branch("        ", bid, m, "1.0")
        parts.append("      </logicTreeBranchSet>")
    parts.append("    </logicTreeBranchingLevel>")
    parts += ["  </logicTree>", "</nrml>"]
    return "\n".join(parts)


def engine_validate(xml_text: str):
    """Validate the logic tree with the engine's own parser/validator.

    Returns (errors, warnings, parse_error, environment_error, spec)."""
    import tempfile
    try:
        from openquake.fdha.logic_tree import nrml_reader, validators
        p = Path(tempfile.mkdtemp()) / "fdha_logic_tree.xml"
        p.write_text(xml_text)
        spec = nrml_reader.parse(p)
        report = validators.validate_spec(spec)
        return list(report.errors), list(report.warnings), None, None, spec
    except Exception as exc:  # parse failure
        message = str(exc)
        if "Numba needs NumPy" in message or (
            "NumPy" in message and "Numba" in message
        ):
            return [], [], None, message, None
        return [], [], message, None, None


def build_sm_lt(rows: list[tuple[str, float]]) -> str:
    """Source-model logic tree over (filename, weight) branches - same NRML
    structure as the shipped trees (e.g. config_norcia_case3_iaea_
    source_model_logic_tree.xml)."""
    branches = "\n".join(
        f'      <logicTreeBranch branchID="b_sm_{k}">\n'
        f"        <uncertaintyModel>{fname}</uncertaintyModel>\n"
        f"        <uncertaintyWeight>{w}</uncertaintyWeight>\n"
        "      </logicTreeBranch>"
        for k, (fname, w) in enumerate(rows))
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<nrml xmlns:gml="http://www.opengis.net/gml"\n'
        '      xmlns="http://openquake.org/xmlns/nrml/0.4">\n'
        '  <logicTree logicTreeID="lt_sm_webgui">\n'
        '    <logicTreeBranchSet uncertaintyType="sourceModel"'
        ' branchSetID="bs_sm_webgui">\n'
        f"{branches}\n"
        "    </logicTreeBranchSet>\n"
        "  </logicTree>\n"
        "</nrml>\n")


def parse_sm_lt(xml_text: str) -> list[tuple[str, float]]:
    """List (source-model filename, weight) branches of a source-model
    logic-tree XML (NRML 0.4, uncertaintyType='sourceModel')."""
    ns = {"n": "http://openquake.org/xmlns/nrml/0.4"}
    root = ET.fromstring(xml_text)
    out = []
    for br in root.iter("{http://openquake.org/xmlns/nrml/0.4}logicTreeBranch"):
        um = br.find("n:uncertaintyModel", ns)
        uw = br.find("n:uncertaintyWeight", ns)
        if um is not None and uw is not None:
            out.append((um.text.strip(), float(uw.text)))
    return out


def parse_fault_traces(xml_path: Path) -> list[dict]:
    """Extract simple fault trace paths from an NRML source-model XML."""
    root = ET.parse(xml_path).getroot()
    traces = []
    for elem in root.iter():
        tag = elem.tag.split("}")[-1]
        if not tag.endswith("FaultSource"):
            continue
        pos_text = None
        for child in elem.iter():
            if child.tag.split("}")[-1] == "posList" and child.text:
                pos_text = child.text
                break
        if not pos_text:
            continue
        values = [float(value) for value in pos_text.split()]
        path = [
            [values[index], values[index + 1]]
            for index in range(0, len(values) - 1, 2)
        ]
        if len(path) >= 2:
            traces.append({
                "source_id": elem.get("id") or "source",
                "name": elem.get("name") or elem.get("id") or "source",
                "path": path,
            })
    return traces


def source_model_files_for_run(jobdir: Path) -> list[Path]:
    """Resolve source-model XML files copied into a run directory."""
    sm_lt = jobdir / "source_model_logic_tree.xml"
    if sm_lt.exists():
        try:
            names = [name for name, _ in parse_sm_lt(sm_lt.read_text())]
            files = [jobdir / name for name in names if (jobdir / name).exists()]
            if files:
                return files
        except Exception:
            pass
    return [
        path for path in sorted(jobdir.glob("*.xml"))
        if path.name not in {"fdha_logic_tree.xml", "source_model_logic_tree.xml"}
    ]


def fault_traces_for_run(jobdir: Path) -> list[dict]:
    """Return all fault traces from source models associated with a run."""
    traces = []
    for xml_path in source_model_files_for_run(jobdir):
        try:
            traces.extend(parse_fault_traces(xml_path))
        except Exception:
            continue
    return traces


def map_view_state(points: list[dict], traces: list[dict]):
    """Create a stable PyDeck viewport from points and fault trace vertices."""
    import pydeck as pdk

    coords = [[point["lon"], point["lat"]] for point in points]
    for trace in traces:
        coords.extend(trace["path"])
    if not coords:
        return pdk.ViewState(latitude=0.0, longitude=0.0, zoom=1.0)

    lons = [coord[0] for coord in coords]
    lats = [coord[1] for coord in coords]
    span = max(max(lons) - min(lons), max(lats) - min(lats), 0.001)
    if span < 0.05:
        zoom = 11.0
    elif span < 0.2:
        zoom = 9.5
    elif span < 1.0:
        zoom = 8.0
    else:
        zoom = 5.5
    return pdk.ViewState(
        latitude=sum(lats) / len(lats),
        longitude=sum(lons) / len(lons),
        zoom=zoom,
        pitch=0,
        bearing=0,
    )


def selected_pydeck_object(event, layer_id: str) -> dict | None:
    """Read the first selected object from a Streamlit PyDeck event."""
    if not event:
        return None
    selection = getattr(event, "selection", None)
    if selection is None and isinstance(event, dict):
        selection = event.get("selection")
    if not selection:
        return None
    objects = getattr(selection, "objects", None)
    if objects is None and isinstance(selection, dict):
        objects = selection.get("objects", {})
    selected = (objects or {}).get(layer_id) or []
    return selected[0] if selected else None


def build_job_ini(cfg: dict) -> str:
    """Render the v5 canonical INI for the configured job (parameter names
    as parsed by openquake/fdha/calc/config_loader.py)."""
    lines = [
        "[general]",
        f"description = {cfg['description']}",
        "calculation_mode = fdha_classical",
        "",
        "[geometry]",
    ]
    if cfg["calc_type"] == "hazard_map":
        lines += [f"region = {cfg['region']}",
                  f"region_grid_spacing = {cfg['grid']}",
                  f"max_distance_km = {cfg['max_dist']}"]
    else:
        lines += [f"sites = {cfg['sites']}"]
    lines += [
        "",
        "[site_params]",
        f"reference_vs30_value = {cfg['vs30']}",
        "",
        "[erf]",
        f"rupture_mesh_spacing = {cfg['mesh']}",
        f"width_of_mfd_bin = {cfg['mfd_bin']}",
        "",
        "[calculation]",
        f"investigation_time = {cfg['investigation_time']}",
        f"displacement_measure_levels = {cfg['dml']}",
        f"r_threshold_km = {cfg['r_threshold_km']}",
        f"near_far_threshold_km = {cfg['near_far_threshold_km']}",
    ]
    if cfg.get("visini_case"):
        lines.append(f"case = {cfg['visini_case']}")
    if cfg["calc_type"] == "hazard_map":
        lines.append(f"return_period = {cfg['return_period']}")
    lines += [
        "fdha_logic_tree_file = fdha_logic_tree.xml",
        "source_model_logic_tree_file = source_model_logic_tree.xml",
        "",
        "[output]",
        "mean = true",
        "quantiles = 0.05 0.16 0.5 0.84 0.95",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Page 1 - Configure
# --------------------------------------------------------------------------
def page_configure() -> None:
    st.header("Configure")

    # ---- Source model ------------------------------------------------------
    st.subheader("Seismic source model & source-model logic tree")
    sm_mode = st.radio(
        "Source-model input",
        ["Built-in example", "Upload source model(s) - build the logic tree",
         "Upload a source-model logic-tree XML"],
        horizontal=True,
        help="The job always runs through a source-model logic tree "
             "([calculation].source_model_logic_tree_file); single models "
             "are wrapped in a one-branch tree with weight 1.0.")
    updir = HERE / "uploads"
    sm_files: list[Path] = []
    sm_lt_text = None
    sm_ok = False
    choice = sm_mode
    geo_defaults = BUILTIN_SOURCES["Norcia Case 3 (IAEA TECDOC-2092)"]

    if sm_mode == "Built-in example":
        choice = st.selectbox("Source model", list(BUILTIN_SOURCES))
        geo_defaults = BUILTIN_SOURCES[choice]
        sm_files = [geo_defaults["xml"]]
        sm_lt_text = build_sm_lt([(geo_defaults["xml"].name, 1.0)])
        sm_ok = True
    elif sm_mode.startswith("Upload source model(s)"):
        ups = st.file_uploader("NRML source model file(s)", type=["xml"],
                               accept_multiple_files=True, key="sm_ups")
        if ups:
            updir.mkdir(exist_ok=True)
            n = len(ups)
            eq = ([round(1.0 / n, 6)] * (n - 1)
                  + [round(1.0 - (n - 1) * round(1.0 / n, 6), 6)])
            rows = []
            cols = st.columns(min(n, 4))
            for k, up in enumerate(ups):
                dest = updir / up.name
                dest.write_bytes(up.getvalue())
                sm_files.append(dest)
                with cols[k % len(cols)]:
                    w = st.number_input(f"weight - {up.name}", min_value=0.0,
                                        max_value=1.0, value=eq[k], step=0.05,
                                        format="%.6f", key=f"smw_{up.name}")
                rows.append((up.name, w))
            total = sum(w for _, w in rows)
            if abs(total - 1.0) <= WEIGHT_TOL:
                st.success(f"OK: source-model weights sum to {total:.6f}")
                sm_ok = True
            else:
                st.error(f"ERROR: source-model weights sum to {total:.6f} - "
                         "must be 1.0 +/- 1e-6")
            sm_lt_text = build_sm_lt(rows)
            with st.expander("Preview: source_model_logic_tree.xml"):
                st.code(sm_lt_text, language="xml")
                st.download_button("Download source_model_logic_tree.xml",
                                   sm_lt_text,
                                   file_name="source_model_logic_tree.xml")
        else:
            st.warning("Upload at least one NRML source model.")
    else:  # upload a ready-made source-model logic tree
        lt_up = st.file_uploader("Source-model logic-tree XML",
                                 type=["xml"], key="smlt_up")
        refs_up = st.file_uploader(
            "Source-model file(s) referenced by the logic tree",
            type=["xml"], accept_multiple_files=True, key="sm_refs")
        if lt_up is not None:
            sm_lt_text = lt_up.getvalue().decode("utf-8", errors="replace")
            try:
                branches = parse_sm_lt(sm_lt_text)
            except Exception as exc:
                st.error(f"Could not parse the logic-tree XML: {exc}")
                branches = []
            if branches:
                st.table([{"source model file": f, "weight": w}
                          for f, w in branches])
                total = sum(w for _, w in branches)
                if abs(total - 1.0) > WEIGHT_TOL:
                    st.warning(f"Branch weights sum to {total:.6f} - the "
                               "engine requires 1.0.")
                updir.mkdir(exist_ok=True)
                by_name = {}
                for up in refs_up or []:
                    dest = updir / up.name
                    dest.write_bytes(up.getvalue())
                    by_name[up.name] = dest
                missing = [f for f, _ in branches if f not in by_name]
                if missing:
                    st.error("Referenced file(s) not uploaded yet: "
                             + ", ".join(f"`{f}`" for f in missing))
                else:
                    sm_files = [by_name[f] for f, _ in branches]
                    sm_ok = abs(total - 1.0) <= WEIGHT_TOL
        else:
            st.warning("Upload the logic-tree XML and its source-model "
                       "files.")

    sources: list = []
    for f in sm_files:
        try:
            ss = list_sources(f)
            if ss:
                with st.expander(f"`{f.name}` - {len(ss)} fault source(s)",
                                 expanded=len(sm_files) == 1):
                    st.table(ss)
                sources.extend(ss)
            else:
                st.error(f"No fault sources found in `{f.name}`.")
                sm_ok = False
        except Exception as exc:
            st.error(f"Could not parse `{f.name}`: {exc}")
            sm_ok = False
    # de-duplicate by source id for the end-branch preview
    sources = list({s["id"]: s for s in sources}.values())

    # ---- Geometry & calculation parameters ---------------------------------
    st.subheader("Geometry and calculation parameters")
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        calc_type = st.radio(
            "Calculation type",
            ["Hazard curve (sites)", "Hazard map (region)"],
            help="The engine auto-detects map mode from the presence of "
                 "[geometry].region (logic_tree/driver.py:1057-1063).")
        is_map = calc_type.startswith("Hazard map")
        if is_map:
            region = st.text_area("region (lon lat corners)",
                                  geo_defaults["region"], height=68)
            grid = st.number_input("region_grid_spacing [deg]",
                                   min_value=0.001,
                                   value=float(geo_defaults["grid"]),
                                   step=0.005, format="%.3f")
            max_dist = st.number_input("max_distance_km", min_value=1.0,
                                       value=float(geo_defaults["max_dist"]))
            sites = ""
        else:
            sites = st.text_area("sites (lon lat, lon lat, ...)",
                                 geo_defaults["sites"], height=68)
            region, grid, max_dist = "", 0.0, 0.0
    with c2:
        # Default 1.0: CalculationConfig, calc/config_loader.py:50
        investigation_time = st.number_input("investigation_time [yr]",
                                             min_value=0.1, value=1.0)
        # Default 0.1: calc/calculators.py:115-117
        r_threshold_km = st.number_input("r_threshold_km", min_value=0.0,
                                         value=0.1, step=0.05, format="%.3f")
        # Default 0.2: calc/calculators.py:123-124
        near_far = st.number_input("near_far_threshold_km", min_value=0.0,
                                   value=0.2, step=0.05, format="%.3f")
    with c3:
        # ERFConfig defaults: calc/config_loader.py:35-36
        mesh = st.number_input("rupture_mesh_spacing [km]", min_value=0.1,
                               value=0.5, step=0.5,
                               help="Coarser spacing runs faster.")
        mfd_bin = st.number_input("width_of_mfd_bin", min_value=0.01,
                                  value=0.1, step=0.05, format="%.2f")
        vs30 = st.number_input("reference_vs30_value [m/s]", min_value=100.0,
                               value=float(geo_defaults["vs30"]))
        return_period = None
        if is_map:
            # Default 100000: calc/hazard_map.py:37
            return_period = st.number_input("return_period [yr]",
                                            min_value=1, value=100000,
                                            step=1000)
    with c4:
        dml = st.text_area("displacement_measure_levels (JSON)", DEFAULT_DML,
                           height=150,
                           help='Format: {"FD": [levels in metres]}')
        try:
            levels = json.loads(dml)["FD"]
            st.caption(f"OK: {len(levels)} displacement levels")
            dml_ok = True
        except Exception as exc:
            st.error(f"Invalid JSON: {exc}")
            dml_ok = False

    # ---- Logic-tree builder -------------------------------------------------
    st.subheader("FDHA logic tree")
    fdha_mode = st.radio(
        "FDHA logic-tree input",
        ["Build in the UI", "Upload fdha_logic_tree.xml"],
        horizontal=True)
    selections: dict = {}
    uploaded_lt = None
    weights_ok = False
    if fdha_mode == "Build in the UI":
        st.caption(
            "Edit model parameters as `key = value` lines - the engine's native "
            "<uncertaintyModel> syntax. Weights within each branch set must sum "
            "to 1.0 (FDLT-001, logic_tree/validators.py:133-143). The default "
            "selection is a light single-branch calculation suitable for a "
            "quick live demonstration."
        )

        def param_prefill(meta: dict) -> str:
            # Only the curated example parameters are prefilled. Optional
            # constructor knobs (e.g. n_sigma) are NOT auto-written: they have
            # working defaults, so pre-filling them made optional tuning
            # parameters look required. They remain documented in the parameter
            # table and can be added by hand when needed.
            return meta.get("prefill", "")

        def doc_table(meta: dict) -> None:
            dp = list(meta.get("doc_params") or [])
            # Optional constructor knobs (e.g. n_sigma) are derived from the
            # model's __init__ signature - they always have a default, so they
            # are surfaced as explicitly NOT required rather than prefilled.
            documented = {r["name"] for r in dp}
            ctor_rows = [
                {"name": k, "default": str(v), "required": False,
                 "allowed": "numeric"}
                for k, v in (meta.get("ctor_defaults") or {}).items()
                if k not in documented
            ]
            rows = dp + ctor_rows
            if rows:
                md = "| param | default | required | allowed |\n|---|---|---|---|\n"
                for r in rows:
                    md += (f"| `{r['name']}` | {r.get('default', '')} | "
                           f"{'**yes**' if r['required'] else 'no'} | "
                           f"{r.get('allowed', '')[:60]} |\n")
                st.markdown(md)
                if any(r["name"] == "style" for r in dp):
                    st.caption("Info: `style` is assigned automatically from "
                               "the source rake when omitted "
                               "(calc/contexts.py, classify_style).")
                if meta.get("doc_page"):
                    st.caption("Full reference: docs/UserManual_Enhanced/models/"
                               f"{meta['doc_page']}")
            else:
                st.caption("No documented parameters - the model runs with "
                           "internal defaults.")

        weights_ok = True
        for utype, label in SLOT_LABELS.items():
            models = REGISTRY["slots"][utype]["models"]
            names = [m["class_name"] for m in models]
            by_name = {m["class_name"]: m for m in models}
            # Each slot holds an ordered list of *branch instances*. The same
            # model may appear more than once (e.g. Youngs2003SecondaryFD with
            # norm_disp_type = AD in one branch and = MD in another); every
            # instance carries its own parameters and weight. A per-slot uid
            # counter gives each instance stable widget keys across reruns.
            rows_key = f"lt_rows_{utype}"
            uid_key = f"lt_uid_{utype}"
            if rows_key not in st.session_state:
                st.session_state[uid_key] = 0
                seeded = []
                for nm in LIGHT_PRESET[utype]:
                    seeded.append({"uid": st.session_state[uid_key],
                                   "class_name": nm})
                    st.session_state[uid_key] += 1
                st.session_state[rows_key] = seeded

            with st.expander(label, expanded=True):
                addcol, btncol = st.columns([3, 1])
                with addcol:
                    to_add = st.selectbox("Add a model branch", names,
                                          key=f"add_{utype}",
                                          label_visibility="collapsed")
                with btncol:
                    if st.button("Add branch", key=f"addbtn_{utype}",
                                 width="stretch"):
                        st.session_state[rows_key].append(
                            {"uid": st.session_state[uid_key],
                             "class_name": to_add})
                        st.session_state[uid_key] += 1
                        st.rerun()

                slot_rows = st.session_state[rows_key]
                # "Free" instances share the user-weighted set; coupled FD
                # instances each carry weight 1.0 inside their own chain.
                def _is_coupled(nm: str) -> bool:
                    return (utype == "fdhaSecondaryFDModel"
                            and nm in COUPLED_FD_TO_SR)
                n_free = sum(1 for r in slot_rows
                             if not _is_coupled(r["class_name"]))
                default_w = round(1.0 / n_free, 6) if n_free else 0.0

                rows = []
                if not slot_rows:
                    st.error("ERROR: add at least one model branch")
                    weights_ok = False
                for k, r in enumerate(slot_rows):
                    name = r["class_name"]
                    uid = r["uid"]
                    meta = by_name.get(name)
                    if meta is None:        # model no longer in the registry
                        continue
                    st.markdown(f"**Branch {k + 1} - `{name}`**")
                    wcol, pcol, dcol = st.columns([1, 2, 2])
                    with wcol:
                        if _is_coupled(name):
                            st.caption(
                                f"chained to `{COUPLED_FD_TO_SR[name]}` - "
                                "weight 1.0 within its chain (the pair "
                                "shares the SR branch weight)")
                            w = 1.0
                        else:
                            wkey = f"w_{utype}_{uid}"
                            st.session_state.setdefault(wkey, default_w)
                            w = st.number_input("weight", min_value=0.0,
                                                max_value=1.0, step=0.05,
                                                format="%.6f", key=wkey)
                        if st.button("Remove", key=f"rm_{utype}_{uid}",
                                     width="stretch"):
                            del st.session_state[rows_key][k]
                            st.rerun()
                    with pcol:
                        pkey = f"p_{utype}_{uid}"
                        st.session_state.setdefault(pkey, param_prefill(meta))
                        params = st.text_area(
                            f"parameters - {name}", height=100, key=pkey,
                            help="One `key = value` per line; leave empty to "
                                 "use model defaults.")
                    with dcol:
                        doc_table(meta)
                    rows.append({"class_name": name, "weight": w,
                                 "params": params})

                checked = [r for r in rows if not _is_coupled(r["class_name"])]
                if checked:
                    total = sum(r["weight"] for r in checked)
                    if abs(total - 1.0) <= WEIGHT_TOL:
                        st.success(f"OK: weights sum to {total:.6f}")
                    else:
                        st.error(f"ERROR: weights sum to {total:.6f} - must be "
                                 "1.0 +/- 1e-6 (FDLT-001)")
                        weights_ok = False
                selections[utype] = rows

        # Cross-slot constraints for engine-coupled distributed families
        # (Visini 2025 SR <-> FD: calc/hazard.py:241, calc/visini.py:247,320-329).
        ssr_names = {r["class_name"] for r in selections["fdhaSecondarySRModel"]}
        sfd_names = {r["class_name"] for r in selections["fdhaSecondaryFDModel"]}
        coupling_ok = True
        for sr, fd in COUPLED_DISTRIBUTED:
            if (sr in ssr_names) != (fd in sfd_names):
                missing, present = (fd, sr) if sr in ssr_names else (sr, fd)
                st.error(f"`{present}` requires `{missing}` - the engine "
                         "computes this model family on a dedicated calculator "
                         "that needs both (calc/hazard.py:241). Add the partner "
                         "model or remove this one.")
                coupling_ok = False
        free_sr = ssr_names - set(COUPLED_SR_TO_FD)
        free_fd = sfd_names - set(COUPLED_FD_TO_SR)
        if bool(free_sr) != bool(free_fd):
            a, b = (("rupture", "displacement") if free_sr
                    else ("displacement", "rupture"))
            st.error(f"The selected distributed {a} model(s) "
                     f"{sorted(free_sr or free_fd)} have no compatible "
                     f"distributed {b} model selected.")
            coupling_ok = False
        weights_ok = weights_ok and coupling_ok
    else:
        lt_up2 = st.file_uploader("fdha_logic_tree.xml (NRML)",
                                  type=["xml"], key="fdha_lt_up")
        if lt_up2 is not None:
            uploaded_lt = lt_up2.getvalue().decode("utf-8",
                                                   errors="replace")
            weights_ok = True
        else:
            st.warning("Upload an FDHA logic-tree XML - it will be "
                       "validated by the engine below.")


    # ---- Live engine validation + end-branch preview --------------------------
    if fdha_mode == "Build in the UI":
        lt_xml = build_fdha_lt_xml(selections) if weights_ok else None
    else:
        lt_xml = uploaded_lt

    # Visini et al. (2025) job-level 'case' parameter ([calculation].case,
    # cf. job_norcia_case3_iaea_curve.ini:18 and the model docs, which mark
    # it Required). case3 = Combination A only - the configuration used by
    # the shipped Norcia benchmark.
    visini_case = None
    if lt_xml and "Visini" in lt_xml:
        visini_case = st.selectbox(
            "Visini et al. (2025) combination case ([calculation].case)",
            ["case3", "case2", "case1"],
            help="Case 3 -> combination A only; Case 2 -> A/B; Case 1 -> "
                 "A/B/C. Note: the combination-C path (case1) currently "
                 "raises an error in the engine (visini.py:305 calls "
                 "get_prob without the required style/pixel_size "
                 "arguments) - prefer case2/case3 until fixed upstream.")
    engine_ok = False
    spec = None
    if lt_xml:
        errors, warnings, parse_err, env_err, spec = engine_validate(lt_xml)
        if env_err:
            st.error(
                "The oq-pfdha engine could not be imported because the Python "
                f"environment has incompatible scientific packages: {env_err}"
            )
            st.code(
                "python -m pip install -e . --upgrade --force-reinstall\n"
                "python -m pip install -r webgui_demo/requirements.txt",
                language="bash",
            )
        elif parse_err:
            st.error(f"Logic tree does not parse: {parse_err}")
        elif errors:
            for e in errors:
                st.error(f"{e.code}: {e.message}")
        else:
            engine_ok = True
            msg = "Logic tree validated by the engine (nrml_reader + validate_spec)"
            if warnings:
                st.warning(msg + " with warnings:\n" +
                           "\n".join(f"- {w.code}: {w.message}" for w in warnings))
            else:
                st.success("OK: " + msg)

    # Enumerate end-branches with the engine's own enumerator so the
    # preview cannot drift from what actually runs.
    n_branches = 0
    style_ok = True
    if spec is not None and engine_ok and sources:
        from openquake.fdha.logic_tree.enumerator import (
            SourceInfo, enumerate_end_branches)
        infos = [SourceInfo(s["id"], float(s["rake"] or 0.0)) for s in sources]
        ebs = enumerate_end_branches(spec, infos)
        n_branches = len(ebs) // max(len(infos), 1)
        st.caption(f"Full enumeration: **{n_branches} end-branch(es) per "
                   "source**. Runtime grows with branches x sites; keep it "
                   "small for a live demonstration.")

        # Applicability check over the enumerated (model, source-style)
        # combinations: hard blocks for pairings the engine cannot run,
        # advisories for ones outside a model's calibrated mechanism.
        blocks: dict[tuple, str] = {}
        warns: dict[tuple, str] = {}
        for eb in ebs:
            for mc in eb.selections.values():
                for c in STYLE_CONSTRAINTS:
                    if (c["prefix"] in mc.class_name
                            and eb.style not in c["intended"]):
                        key = (mc.class_name, eb.source_id, eb.style)
                        (blocks if c["kind"] == "block" else warns)[key] = \
                            c["message"]
        for (cn, sid, sty), msg in sorted(blocks.items()):
            st.error(f"`{cn}` on source `{sid}` ({sty} faulting): {msg}")
            style_ok = False
        for (cn, sid, sty), msg in sorted(warns.items()):
            st.warning(f"`{cn}` on source `{sid}` ({sty} faulting): {msg}")
        with st.expander(f"Enumerated end-branches ({len(ebs)} total)"):
            rows = [{
                "source": eb.source_id, "style": eb.style,
                "principal SR": eb.selections["primary_surf_rup"].class_name,
                "principal FD": eb.selections["primary_surf_displ"].class_name,
                "distributed SR": eb.selections["secondary_surf_rup"].class_name,
                "distributed FD": eb.selections["secondary_surf_displ"].class_name,
                "weight": round(eb.weight, 6),
            } for eb in ebs]
            st.dataframe(rows, width="stretch")
            for sid in sorted({r["source"] for r in rows}):
                tot = sum(r["weight"] for r in rows if r["source"] == sid)
                mark = "OK" if abs(tot - 1.0) <= 1e-6 else "ERROR"
                st.caption(f"{mark} source `{sid}`: weights sum to {tot:.6f}")

    with st.expander("Preview: fdha_logic_tree.xml"):
        if lt_xml:
            st.code(lt_xml, language="xml")
            st.download_button("Download fdha_logic_tree.xml", lt_xml,
                               file_name="fdha_logic_tree.xml")
        else:
            st.warning("Fix the errors above to generate the XML.")

    st.session_state["config"] = {
        "description": f"webgui job ({choice})",
        "source_label": choice,
        "sm_files": [str(f) for f in sm_files],
        "sm_lt_text": sm_lt_text,
        "calc_type": "hazard_map" if is_map else "hazard_curve",
        "sites": sites.replace("\n", " ").strip(),
        "region": region.replace("\n", " ").strip(),
        "grid": grid, "max_dist": max_dist, "vs30": vs30,
        "mesh": mesh, "mfd_bin": mfd_bin,
        "investigation_time": investigation_time,
        "r_threshold_km": r_threshold_km,
        "near_far_threshold_km": near_far,
        "return_period": return_period,
        "dml": dml.replace("\n", " ").strip(),
        "selections": selections,
        "visini_case": visini_case,
        "n_branches": n_branches,
        "valid": bool(weights_ok and engine_ok and dml_ok and sm_ok
                      and style_ok and sm_files),
        "lt_xml": lt_xml,
    }


# --------------------------------------------------------------------------
# Page 2 - Run (real calculation)
# --------------------------------------------------------------------------
def page_run() -> None:
    st.header("Run")
    cfg = st.session_state.get("config")
    if cfg is None:
        st.warning("No configuration yet - visit **1. Configure** first.")
        return

    st.subheader("Job summary")
    c1, c2, c3 = st.columns(3)
    c1.metric("Source model", cfg["source_label"].split(" (")[0])
    c1.metric("Calculation type", cfg["calc_type"].replace("_", " "))
    c2.metric("End-branches", cfg["n_branches"])
    c2.metric("r_threshold_km", f'{cfg["r_threshold_km"]} km')
    c3.metric("rupture_mesh_spacing", f'{cfg["mesh"]} km')
    if cfg["return_period"]:
        c3.metric("return_period", f'{cfg["return_period"]} yr')
    with st.expander("job.ini to be executed"):
        st.code(build_job_ini(cfg), language="ini")

    if not cfg["valid"]:
        st.error("Configuration is incomplete or invalid - fix the issues "
                 "flagged on **1. Configure** before running.")
        return

    est = cfg["n_branches"]
    if est > 8:
        st.warning(f"{est} end-branches - this is a full calculation, not a "
                   "quick demo; it may take many minutes.")

    if st.button("Run calculation", type="primary"):
        stamp = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
        jobdir = RUNS / f"run_{stamp}"
        outdir = jobdir / "out"
        jobdir.mkdir(parents=True, exist_ok=True)
        for f in cfg["sm_files"]:
            shutil.copy(f, jobdir / Path(f).name)
        (jobdir / "source_model_logic_tree.xml").write_text(cfg["sm_lt_text"])
        (jobdir / "fdha_logic_tree.xml").write_text(cfg["lt_xml"])
        ini = jobdir / "job.ini"
        ini.write_text(build_job_ini(cfg))

        log_buf = io.StringIO()
        handler = logging.StreamHandler(log_buf)
        handler.setLevel(logging.INFO)
        logging.getLogger().addHandler(handler)
        t0 = _dt.datetime.now()
        try:
            with st.status("Running the oq-pfdha engine...", expanded=True) as status:
                st.write(f"Job directory: `{jobdir}`")
                from openquake.fdha.logic_tree.driver import FdhaLogicTree
                result = FdhaLogicTree.from_ini(ini).run(outdir=outdir)
                dt = (_dt.datetime.now() - t0).total_seconds()
                status.update(label=f"Completed in {dt:.1f} s",
                              state="complete")
            st.session_state["last_run"] = {
                "outdir": str(outdir), "jobdir": str(jobdir),
                "mode": result.mode, "elapsed_s": dt,
            }
            st.success(f"Calculation finished ({result.mode}, {dt:.1f} s) - "
                       "see **3. Results**.")
        except Exception:
            st.error("The engine raised an error - full traceback below.")
            st.exception(Exception("engine failure"))
            import traceback
            st.code(traceback.format_exc())
        finally:
            logging.getLogger().removeHandler(handler)
        log_text = log_buf.getvalue().strip()
        if log_text:
            with st.expander("Engine log"):
                st.code(log_text[-8000:])


# --------------------------------------------------------------------------
# Page 3 - Results (from the last real run)
# --------------------------------------------------------------------------
def page_results() -> None:
    st.header("Results")
    run = st.session_state.get("last_run")
    if not run:
        st.warning("No completed run in this session - execute one on "
                   "**2. Run** first.")
        return
    outdir = Path(run["outdir"])
    st.caption(f"Run output: `{outdir}` - mode **{run['mode']}**, "
               f"{run['elapsed_s']:.1f} s")

    import pandas as pd

    if run["mode"] == "hazard_curve":
        agg = outdir / "aggregate_hazard.csv"
        if not agg.exists():
            st.error(f"Expected output not found: {agg}")
            return
        df = pd.read_csv(agg, comment="#")
        # Geographic hazard context map removed: the interactive PyDeck basemap
        # made the Results page slow (tile downloads + on_select="rerun" reran
        # the whole page on every map click). Site selection is handled by the
        # selectbox below instead.
        selected_site_id = None

        st.subheader("Hazard curves (weighted mean + fractiles)")
        site_ids = sorted(df["site_id"].unique())
        default_index = (
            site_ids.index(selected_site_id)
            if selected_site_id in site_ids else 0
        )
        chosen = st.selectbox(
            "Site", site_ids,
            index=default_index,
            format_func=lambda s: (
                f"site {s} ({df[df.site_id == s].lon.iloc[0]:.3f}, "
                f"{df[df.site_id == s].lat.iloc[0]:.3f})"))
        d = df[df["site_id"] == chosen]

        import plotly.graph_objects as go
        fig = go.Figure()
        if "quantile-0.84" in d:
            fig.add_trace(go.Scatter(x=d["D0"], y=d["quantile-0.84"],
                                     line=dict(width=0), showlegend=False,
                                     hoverinfo="skip"))
            fig.add_trace(go.Scatter(x=d["D0"], y=d["quantile-0.16"],
                                     fill="tonexty",
                                     fillcolor="rgba(242,118,43,0.20)",
                                     line=dict(width=0),
                                     name="16-84% fractiles"))
        for q, dash, lbl in [("quantile-0.05", "dot", "5 / 95%"),
                             ("quantile-0.95", "dot", None),
                             ("quantile-0.5", "dash", "median")]:
            if q in d:
                fig.add_trace(go.Scatter(
                    x=d["D0"], y=d[q], name=lbl, showlegend=lbl is not None,
                    line=dict(color=CLAY_500, dash=dash, width=1.2)))
        # per-branch spaghetti
        branch_dir = outdir / "hazard_curves"
        branch_files = sorted(branch_dir.glob("branch_*.csv"))
        if len(branch_files) > 1 and st.checkbox(
                f"Show all {len(branch_files)} branch curves", value=True):
            for bf in branch_files:
                b = pd.read_csv(bf, comment="#")
                b = b[b["site_id"] == chosen]
                fig.add_trace(go.Scatter(x=b["D0"], y=b["annual_rate"],
                                         line=dict(color="#ab9b80", width=0.8),
                                         showlegend=False, hoverinfo="skip"))
        fig.add_trace(go.Scatter(x=d["D0"], y=d["mean"], name="weighted mean",
                                 line=dict(color=ACCENT, width=3.5)))
        style_fig(fig)
        fig.update_xaxes(type="log", title="Displacement (m)")
        fig.update_yaxes(type="log",
                         title="Annual rate of exceedance (yr^-1)")
        st.plotly_chart(fig, width="stretch")

        # When the branch-to-branch spread is narrower than the plotted line
        # width, say so explicitly - otherwise the band looks "missing".
        if "quantile-0.84" in d and len(branch_files) > 1:
            with pd.option_context("mode.chained_assignment", None):
                rel = ((d["quantile-0.84"] - d["quantile-0.16"])
                       / d["mean"].where(d["mean"] > 0)).max()
            if pd.notna(rel) and rel < 0.02:
                st.info(
                    f"The 16-84% fractile band spans at most "
                    f"**{rel:.2%} of the mean** at this site - the branch "
                    "curves nearly coincide, so the band and spaghetti are "
                    "hidden under the mean line. This typically happens "
                    "when all branches share the same principal models and "
                    "differ only in distributed models whose contribution "
                    "is small at this site. Use the relative-spread view "
                    "below to inspect the differences.")
            if st.checkbox("Show relative spread (curves / weighted mean)",
                           value=False):
                rfig = go.Figure()
                base = d["mean"].where(d["mean"] > 0)
                rfig.add_trace(go.Scatter(
                    x=d["D0"], y=d["quantile-0.84"] / base,
                    line=dict(width=0), showlegend=False, hoverinfo="skip"))
                rfig.add_trace(go.Scatter(
                    x=d["D0"], y=d["quantile-0.16"] / base, fill="tonexty",
                    fillcolor="rgba(242,118,43,0.20)", line=dict(width=0),
                    name="16-84% fractiles"))
                for q, dash, lbl in [("quantile-0.05", "dot", "5 / 95%"),
                                     ("quantile-0.95", "dot", None),
                                     ("quantile-0.5", "dash", "median")]:
                    rfig.add_trace(go.Scatter(
                        x=d["D0"], y=d[q] / base, name=lbl,
                        showlegend=lbl is not None,
                        line=dict(color=CLAY_500, dash=dash, width=1.2)))
                for bf in branch_files:
                    b = pd.read_csv(bf, comment="#")
                    b = b[b["site_id"] == chosen]
                    rfig.add_trace(go.Scatter(
                        x=b["D0"], y=b["annual_rate"].to_numpy() / base.to_numpy(),
                        line=dict(color="#ab9b80", width=0.8),
                        showlegend=False, hoverinfo="skip"))
                rfig.add_hline(y=1.0, line_color=ACCENT, line_width=2.5)
                style_fig(rfig, height=440)
                rfig.update_xaxes(type="log", title="Displacement (m)")
                rfig.update_yaxes(title="Rate / weighted mean (-)")
                st.plotly_chart(rfig, width="stretch")
        st.download_button("Download aggregate_hazard.csv", agg.read_bytes(),
                           file_name="aggregate_hazard.csv", mime="text/csv")
    else:
        st.subheader("Displacement hazard map")
        agg_dir = outdir / "aggregate"
        mean_csv = agg_dir / "displacement_map_mean.csv"
        if not mean_csv.exists():
            st.error(f"Expected output not found: {mean_csv}")
            return
        layers = ["mean"] + sorted(
            p.stem.replace("displacement_map_", "")
            for p in agg_dir.glob("displacement_map_quantile-*.csv"))
        which = st.radio("Layer", layers, horizontal=True)
        m = pd.read_csv(agg_dir / f"displacement_map_{which}.csv", comment="#")
        col = [c for c in m.columns if c.startswith("displ")][0]
        import numpy as np
        import pydeck as pdk
        pos = m[m[col] > 0].copy()
        if pos.empty:
            st.info("All displacement values are zero for this layer.")
            return
        lo, hi = np.log10(pos[col].min()), np.log10(pos[col].max())
        t = (np.log10(pos[col]) - lo) / max(hi - lo, 1e-12)
        pos["color"] = [
            [int(59 + 183 * x), int(130 - 12 * x), int(246 - 203 * x), 205]
            for x in t
        ]
        grid_points = [
            {
                "site_id": int(row.site_id),
                "lon": float(row.lon),
                "lat": float(row.lat),
                "displacement": float(getattr(row, col)),
            }
            for row in pos.itertuples(index=False)
        ]
        traces = fault_traces_for_run(Path(run["jobdir"]))
        map_layers = []
        if traces:
            map_layers.append(pdk.Layer(
                "PathLayer",
                id="fault-traces",
                data=traces,
                get_path="path",
                get_color=[242, 118, 43, 230],
                get_width=6,
                width_min_pixels=3,
                rounded=True,
                pickable=False,
            ))
        map_layers.append(pdk.Layer(
            "ScatterplotLayer",
            id="hazard-map-sites",
            data=pos,
            get_position=["lon", "lat"],
            get_fill_color="color",
            get_line_color=[14, 23, 39, 80],
            get_line_width=1,
            get_radius=150,
            radius_min_pixels=3,
            radius_max_pixels=10,
            pickable=True,
            auto_highlight=True,
        ))
        map_event = st.pydeck_chart(
            pdk.Deck(
                layers=map_layers,
                initial_view_state=map_view_state(grid_points, traces),
                map_style="https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
                tooltip={
                    "html": (
                        "<b>grid site {site_id}</b><br/>"
                        "lon {lon}<br/>lat {lat}<br/>"
                        f"{col}: {{{col}}} m"
                    ),
                    "style": {"fontFamily": "Hanken Grotesk"},
                },
            ),
            key=f"hazard_map_{which}",
            height=560,
            on_select="rerun",
            selection_mode="single-object",
        )
        selected_cell = selected_pydeck_object(map_event, "hazard-map-sites")
        if selected_cell:
            st.metric(
                f"Selected grid site {int(selected_cell['site_id'])}",
                f"{float(selected_cell[col]):.6g} m",
            )
        st.download_button(f"Download displacement_map_{which}.csv",
                           (agg_dir / f"displacement_map_{which}.csv").read_bytes(),
                           file_name=f"displacement_map_{which}.csv",
                           mime="text/csv")

    # ---- Diagnostics & full download -----------------------------------------
    st.subheader("Diagnostics")
    for rep in sorted(outdir.glob("source_model_branches/*/validator_report.txt")):
        with st.expander(f"Validator report - {rep.parent.name}"):
            st.code(rep.read_text())
    manifest = outdir / "manifest.json"
    if manifest.exists():
        with st.expander("manifest.json (branches, weights, outputs)"):
            st.json(json.loads(manifest.read_text()))

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in outdir.rglob("*"):
            if f.is_file():
                zf.write(f, f.relative_to(outdir.parent))
    st.download_button("Download complete output directory (ZIP)",
                       buf.getvalue(), file_name=f"{outdir.parent.name}.zip",
                       mime="application/zip")


# --------------------------------------------------------------------------
# Navigation + footer
# --------------------------------------------------------------------------
st.sidebar.markdown(
    "<div class='pfdha-side-brand'>"
    f"{LOGO_MARK}"
    "<div><div class='t'>oq-pfdha</div>"
    "<div class='s'>Fault displacement hazard</div></div>"
    "</div>",
    unsafe_allow_html=True,
)
page = st.sidebar.radio("Workflow", ["1. Configure", "2. Run", "3. Results"])

if page.startswith("1"):
    page_configure()
elif page.startswith("2"):
    page_run()
else:
    page_results()

st.divider()
st.markdown(
    "<div style='text-align:center; color:#655647; font-size:0.92em; "
    "line-height:1.8'>"
    "<b style='color:#1b2c4b'>oq-pfdha</b> - Probabilistic Fault "
    "Displacement Hazard Analysis - GNU AGPL v3.0-or-later<br>"
    "Cite: Chen, Y.-S. (2025). <i>openquake.fdha: Python tools for "
    "probabilistic fault displacement hazard analysis</i> (v1.0.0) "
    "[Software]. OGS. "
    "<a href='https://github.com/vup1120/oq-pfdha' "
    "style='color:#3b82f6'>github.com/vup1120/oq-pfdha</a>"
    " (CITATION.cff)<br>"
    "Built on the OpenQuake Engine: Pagani, M., et al. (2014). "
    "<i>OpenQuake Engine: An Open Hazard (and Risk) Software for the Global "
    "Earthquake Model</i>. Seismological Research Letters, 85(3), 692-702 "
    "(Global Earthquake Model, GEM).<br>"
    "<b>Prototype interface</b> - review configurations and verify results "
    "independently before use in production hazard assessment."
    "</div>",
    unsafe_allow_html=True,
)
