"""oq-pfdha web GUI — demonstration prototype (Streamlit).

Visual proof-of-concept of a web interface for Probabilistic Fault
Displacement Hazard Analysis. It demonstrates the user workflow only:
no real calculation is performed; results shown on the Results page are
pre-computed Norcia Case 3 (IAEA TECDOC-2092) benchmark outputs copied
under webgui_demo/data/ (see data/norcia_case3/PROVENANCE.md).

Model lists come exclusively from registry.json, a snapshot of the actual
oq-pfdha model registry generated by generate_registry.py (which imports
the real model packages — see that script's docstring for provenance).

Run:  streamlit run webgui_demo/app.py
"""
from __future__ import annotations

import json
import time
from pathlib import Path

import streamlit as st

HERE = Path(__file__).parent
REGISTRY = json.loads((HERE / "registry.json").read_text())

# Display order and labels for the four logic-tree slots
# (uncertaintyType values from openquake/fdha/logic_tree/types.py:7-12).
SLOT_LABELS = {
    "fdhaPrimarySRModel": "1 — Principal surface rupture (probability)",
    "fdhaPrimaryFDModel": "2 — Principal fault displacement",
    "fdhaSecondarySRModel": "3 — Distributed surface rupture (probability)",
    "fdhaSecondaryFDModel": "4 — Distributed fault displacement",
}

# Weight tolerance mirrors validator rule FDLT-001
# (openquake/fdha/logic_tree/validators.py:133-143).
WEIGHT_TOL = 1e-6

st.set_page_config(page_title="oq-pfdha demo GUI", page_icon="🌍", layout="wide")


# --------------------------------------------------------------------------
# Logic-tree NRML serialization (single file, schema per
# openquake/fdha/logic_tree/nrml_reader.py:24-56)
# --------------------------------------------------------------------------
def build_nrml(selections: dict) -> str:
    """Serialize the 4-slot model selection to one NRML logic-tree XML."""
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<nrml xmlns="http://openquake.org/xmlns/nrml/0.4">',
        '  <logicTree logicTreeID="lt_fdha_webgui_demo">',
    ]
    for i, (utype, models) in enumerate(selections.items(), start=1):
        slot = REGISTRY["slots"][utype]["package"].rsplit(".", 1)[-1]
        parts.append(
            f'    <logicTreeBranchingLevel branchingLevelID="bl_{i}_{slot}">'
        )
        parts.append(
            f'      <logicTreeBranchSet branchSetID="bs_{i}_{slot}"'
            f' uncertaintyType="{utype}">'
        )
        for m in models:
            body = f"[{m['class_name']}]"
            if m.get("n_sigma") is not None:
                body += f"\nn_sigma = {m['n_sigma']}"
            parts += [
                f'        <logicTreeBranch branchID="{m["class_name"].upper()}_{i}">',
                f"          <uncertaintyModel><![CDATA[{body}]]></uncertaintyModel>",
                f"          <uncertaintyWeight>{m['weight']}</uncertaintyWeight>",
                "        </logicTreeBranch>",
            ]
        parts += ["      </logicTreeBranchSet>", "    </logicTreeBranchingLevel>"]
    parts += ["  </logicTree>", "</nrml>"]
    return "\n".join(parts)


# --------------------------------------------------------------------------
# Page 1 — Configure
# --------------------------------------------------------------------------
def page_configure() -> None:
    st.header("Configure")

    # ---- Source model -----------------------------------------------------
    st.subheader("Seismic source model")
    col1, col2 = st.columns(2)
    with col1:
        source = st.selectbox(
            "Source model",
            ["Norcia Case 3 (built-in example)"],
            help="NRML source model with the MVFS and NFS normal faults "
                 "(IAEA TECDOC-2092, Section 7).",
        )
    with col2:
        up = st.file_uploader("…or upload a NRML source model (XML)", type=["xml"])
        if up is not None:
            st.info(
                f"Received **{up.name}** — accepted by filename only. "
                "Parsing uploaded source models is out of scope for this demo; "
                "the calculation always uses the built-in Norcia Case 3 model."
            )

    # ---- Calculation parameters -------------------------------------------
    st.subheader("Calculation parameters")
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        # Fixed: written in all shipped jobs (e.g. job_norcia_case3_iaea_curve.ini:3);
        # not varied in this demo.
        st.text_input("calculation_mode", "fdha_classical", disabled=True)
        calc_type = st.radio(
            "Calculation type",
            ["Hazard curve (sites)", "Hazard map (region)"],
            help="Auto-detected by the engine from [geometry]: presence of "
                 "'region' selects map mode (logic_tree/driver.py:1057-1063).",
        )
    with c2:
        # Default 1.0: CalculationConfig, calc/config_loader.py:50
        investigation_time = st.number_input(
            "investigation_time [yr]", min_value=0.1, value=1.0, step=0.5
        )
        # Default 0.1: calc/calculators.py:115-117 (and calc/hazard_map.py:38)
        r_threshold_km = st.number_input(
            "r_threshold_km", min_value=0.0, value=0.1, step=0.05, format="%.3f",
            help="Principal vs distributed split distance.",
        )
    with c3:
        # Default 0.2: calc/calculators.py:123-124
        near_far_threshold_km = st.number_input(
            "near_far_threshold_km", min_value=0.0, value=0.2, step=0.05,
            format="%.3f",
            help="Near/far regime threshold used within distributed models "
                 "(e.g. Visini 2025).",
        )
        return_period = None
        if calc_type.startswith("Hazard map"):
            # Default 100000: calc/hazard_map.py:37 (and logic_tree/driver.py:251-252)
            return_period = st.number_input(
                "return_period [yr] (maps only)", min_value=1, value=100000,
                step=1000,
            )
    with c4:
        if calc_type.startswith("Hazard curve"):
            # Sites of the built-in job: job_norcia_case3_iaea_curve.ini:6
            st.text_area(
                "[geometry] sites (lon lat, …)",
                "13.278 42.767, 13.188 42.749, 13.212 42.853",
                disabled=True, height=68,
                help="PF, MS, SL sites of the Norcia Case 3 exercise "
                     "(fixed in this demo).",
            )
        else:
            # Region of the built-in map job: job_norcia_case3_iaea_map.ini:6-7
            st.text_area(
                "[geometry] region / grid",
                "13.05 42.65, 13.35 42.65, 13.35 42.95, 13.05 42.95\n"
                "region_grid_spacing = 0.005",
                disabled=True, height=68,
                help="Fixed to the Norcia Case 3 map job in this demo.",
            )
    st.caption(
        "Distribution truncation is **not** a job-level INI parameter in "
        "oq-pfdha; it is the per-model `n_sigma` parameter set in the logic "
        "tree below for models that support it."
    )

    # ---- Logic-tree builder -----------------------------------------------
    st.subheader("FDHA logic tree")
    st.caption(
        "Pick one or more models per component; weights within each branch "
        "set must sum to 1.0 (validator rule FDLT-001, "
        "logic_tree/validators.py:133-143). Model lists are a snapshot of "
        "the actual oq-pfdha registry (registry.json)."
    )

    selections: dict = {}
    all_valid = True
    for utype, label in SLOT_LABELS.items():
        models = REGISTRY["slots"][utype]["models"]
        names = [m["class_name"] for m in models]
        by_name = {m["class_name"]: m for m in models}
        with st.expander(label, expanded=True):
            chosen = st.multiselect(
                "Models", names, default=names[:1], key=f"ms_{utype}",
                label_visibility="collapsed",
            )
            rows = []
            if chosen:
                n = len(chosen)
                # Prefill equal weights that sum exactly to 1.0
                eq = [round(1.0 / n, 6)] * (n - 1)
                eq.append(round(1.0 - sum(eq), 6))
                cols = st.columns(min(n, 4))
                for k, name in enumerate(chosen):
                    with cols[k % len(cols)]:
                        w = st.number_input(
                            f"weight — {name}", min_value=0.0, max_value=1.0,
                            value=eq[k], step=0.05, format="%.6f",
                            key=f"w_{utype}_{name}",
                        )
                        row = {"class_name": name, "weight": w}
                        ns_def = by_name[name].get("n_sigma_default")
                        if ns_def is not None:
                            # Default introspected from the model __init__
                            # (see generate_registry.py docstring for refs).
                            row["n_sigma"] = st.number_input(
                                f"n_sigma — {name}", min_value=0.5,
                                value=float(ns_def), step=0.5,
                                key=f"ns_{utype}_{name}",
                            )
                        rows.append(row)
                total = sum(r["weight"] for r in rows)
                if abs(total - 1.0) <= WEIGHT_TOL:
                    st.success(f"✓ weights sum to {total:.6f}")
                else:
                    st.error(
                        f"✗ weights sum to {total:.6f} — must be 1.0 ± 1e-6 "
                        "(FDLT-001). Fix before running."
                    )
                    all_valid = False
            else:
                st.error("✗ select at least one model")
                all_valid = False
            selections[utype] = rows

    nrml_xml = build_nrml(selections) if all_valid else None
    with st.expander("Preview: fdha_logic_tree.xml (single NRML file)"):
        if nrml_xml:
            st.code(nrml_xml, language="xml")
        else:
            st.warning("Logic tree is invalid — fix the errors above to "
                       "generate the NRML preview.")

    # Persist for the Run / Results pages
    st.session_state["config"] = {
        "source_model": source,
        "calc_type": "hazard_map" if calc_type.startswith("Hazard map") else
                     "hazard_curve",
        "investigation_time": investigation_time,
        "r_threshold_km": r_threshold_km,
        "near_far_threshold_km": near_far_threshold_km,
        "return_period": return_period,
        "selections": selections,
        "lt_valid": all_valid,
        "nrml_xml": nrml_xml,
    }


# --------------------------------------------------------------------------
# Page 2 — Run (simulated; demo displays pre-computed benchmark outputs)
# --------------------------------------------------------------------------
def page_run() -> None:
    st.header("Run")
    cfg = st.session_state.get("config")
    if cfg is None:
        st.warning("No configuration yet — visit **1 · Configure** first.")
        return

    st.subheader("Configuration summary")
    c1, c2, c3 = st.columns(3)
    c1.metric("Source model", "Norcia Case 3")
    c1.metric("Calculation type", cfg["calc_type"].replace("_", " "))
    c2.metric("investigation_time", f'{cfg["investigation_time"]} yr')
    c2.metric("r_threshold_km", f'{cfg["r_threshold_km"]} km')
    c3.metric("near_far_threshold_km", f'{cfg["near_far_threshold_km"]} km')
    if cfg["return_period"]:
        c3.metric("return_period", f'{cfg["return_period"]} yr')
    n_branches = 1
    for rows in cfg["selections"].values():
        n_branches *= max(len(rows), 1)
    st.metric("Logic-tree end-branches (full enumeration)", n_branches)
    with st.expander("Selected models and weights"):
        for utype, rows in cfg["selections"].items():
            st.markdown(f"**{SLOT_LABELS[utype]}**")
            for r in rows:
                extra = f", n_sigma = {r['n_sigma']}" if r.get("n_sigma") is not None else ""
                st.markdown(f"- `{r['class_name']}` — weight {r['weight']}{extra}")

    if not cfg["lt_valid"]:
        st.error(
            "Logic-tree validation failed (weights must sum to 1.0 per "
            "branch set). Fix the configuration before running."
        )
        return

    if st.button("▶ Run calculation", type="primary"):
        bar = st.progress(0, text="Enumerating logic-tree branches…")
        steps = [
            "Enumerating logic-tree branches…",
            "Building rupture contexts…",
            "Evaluating principal models…",
            "Evaluating distributed models…",
            "Aggregating branch rates…",
        ]
        for i, msg in enumerate(steps):
            time.sleep(0.8)  # simulated only — no computation happens
            bar.progress((i + 1) / len(steps), text=msg)
        st.session_state["ran"] = True
        st.success("Done — see **3 · Results**.")

    if st.session_state.get("ran"):
        st.info(
            "**DEMO MODE — displaying pre-computed Norcia Case 3 results** "
            "(IAEA TECDOC-2092 benchmark). The button above did not run a "
            "real calculation; your model selection does not change the "
            "displayed outputs."
        )


# --------------------------------------------------------------------------
# Page 3 — Results (reads pre-computed CSVs from webgui_demo/data/)
# --------------------------------------------------------------------------
DATA = HERE / "data" / "norcia_case3"
SITE_NAMES = {0: "PF (13.278, 42.767)", 1: "MS (13.188, 42.749)",
              2: "SL (13.212, 42.853)"}  # order from job_norcia_case3_iaea_curve.ini:6
FRACTILES = ["quantile-0.05", "quantile-0.16", "quantile-0.5",
             "quantile-0.84", "quantile-0.95"]


@st.cache_data
def load_curves():
    import pandas as pd
    return pd.read_csv(DATA / "aggregate_hazard.csv")


@st.cache_data
def load_map(which: str):
    import pandas as pd
    return pd.read_csv(DATA / "map" / f"displacement_map_{which}.csv",
                       comment="#")


def page_results() -> None:
    st.header("Results")
    if not st.session_state.get("ran"):
        st.warning("No results yet — press **Run calculation** on page 2 first.")
        return
    st.info("**DEMO MODE** — pre-computed Norcia Case 3 outputs "
            "(see webgui_demo/data/norcia_case3/PROVENANCE.md).")

    # ---- Hazard curves -----------------------------------------------------
    st.subheader("Hazard curves (mean + fractiles)")
    df = load_curves()
    sites = sorted(df["site_id"].unique())
    chosen = st.selectbox("Site", sites,
                          format_func=lambda s: SITE_NAMES.get(s, str(s)))
    d = df[df["site_id"] == chosen]

    import plotly.graph_objects as go
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=d["D0"], y=d["quantile-0.84"], line=dict(width=0),
        showlegend=False, hoverinfo="skip"))
    fig.add_trace(go.Scatter(
        x=d["D0"], y=d["quantile-0.16"], fill="tonexty",
        fillcolor="rgba(170,51,119,0.15)", line=dict(width=0),
        name="16–84% fractiles"))
    for q, dash in [("quantile-0.05", "dot"), ("quantile-0.95", "dot"),
                    ("quantile-0.5", "dash")]:
        fig.add_trace(go.Scatter(x=d["D0"], y=d[q], name=q,
                                 line=dict(color="#888888", dash=dash, width=1.2)))
    fig.add_trace(go.Scatter(x=d["D0"], y=d["mean"], name="weighted mean",
                             line=dict(color="#AA3377", width=3.5)))
    fig.update_xaxes(type="log", title="Displacement (m)")
    # Values are annual exceedance RATES (column 'mean'/'annual_rate' in the
    # engine outputs), not probabilities — labelled accordingly.
    fig.update_yaxes(type="log", title="Annual rate of exceedance (1/yr)")
    fig.update_layout(height=480, margin=dict(t=10),
                      legend=dict(orientation="h", y=-0.25))
    st.plotly_chart(fig, use_container_width=True)

    st.download_button(
        "⬇ Download hazard curves (CSV)",
        (DATA / "aggregate_hazard.csv").read_bytes(),
        file_name="aggregate_hazard.csv", mime="text/csv")

    # ---- Hazard map ----------------------------------------------------------
    st.subheader("Hazard map (displacement at return period = 100 000 yr)")
    which = st.radio(
        "Layer", ["mean"] + [f.replace("quantile-", "quantile ") for f in FRACTILES],
        horizontal=True)
    key = which.replace("quantile ", "quantile-")
    m = load_map(key)
    col = "displ_mean" if key == "mean" else [c for c in m.columns
                                              if c.startswith("displ")][0]
    import numpy as np
    import pydeck as pdk
    pos = m[m[col] > 0].copy()
    lo, hi = np.log10(pos[col].min()), np.log10(pos[col].max())
    t = (np.log10(pos[col]) - lo) / max(hi - lo, 1e-12)
    pos["color"] = [[int(40 + 215 * x), int(60 * (1 - x)), int(140 * (1 - x)), 200]
                    for x in t]
    layer = pdk.Layer(
        "ScatterplotLayer", data=pos,
        get_position=["lon", "lat"], get_fill_color="color",
        get_radius=180, pickable=True)
    st.pydeck_chart(pdk.Deck(
        layers=[layer],
        initial_view_state=pdk.ViewState(latitude=42.80, longitude=13.20,
                                         zoom=10.2),
        tooltip={"text": f"{col}: {{{col}}} m"},
        map_style=None))
    st.caption(
        f"Sites with zero displacement omitted; colour = log10({col}), "
        "dark red = highest. MVFS and NFS fault corridors are visible as "
        "the two coloured bands."
    )
    st.download_button(
        f"⬇ Download map layer ({key}, CSV)",
        (DATA / "map" / f"displacement_map_{key}.csv").read_bytes(),
        file_name=f"displacement_map_{key}.csv", mime="text/csv")


# --------------------------------------------------------------------------
# Navigation
# --------------------------------------------------------------------------
st.sidebar.title("oq-pfdha — demo GUI")
page = st.sidebar.radio("Navigation", ["1 · Configure", "2 · Run", "3 · Results"])
st.sidebar.warning(
    "**DEMO MODE** — no real calculation is performed. Results are "
    "pre-computed Norcia Case 3 (IAEA TECDOC-2092) benchmark outputs."
)

if page.startswith("1"):
    page_configure()
elif page.startswith("2"):
    page_run()
else:
    page_results()
